//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Payables {
    
    public partial class PaymentRequest {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlBtnsContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSoxApprovedStatus;
        protected LAjitControls.LAjitImageButton imgbtnIsApproved;
        protected System.Web.UI.HtmlControls.HtmlTableRow trEntryBank;
        protected System.Web.UI.WebControls.Label lblEntryBank;
        protected LAjitControls.LAjitDropDownList ddlEntryBank;
        protected LAjitControls.LAjitRequiredFieldValidator reqEntryBank;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPaymentDate;
        protected System.Web.UI.WebControls.Label lblPaymentDate;
        protected LAjitControls.LAjitTextBox txtPaymentDate;
        protected LAjitControls.LAjitRequiredFieldValidator reqPaymentDate;
        protected System.Web.UI.HtmlControls.HtmlTableRow trStartCheck;
        protected System.Web.UI.WebControls.Label lblStartCheck;
        protected LAjitControls.LAjitTextBox txtStartCheck;
        protected LAjitControls.LAjitRequiredFieldValidator reqStartCheck;
        protected LAjitControls.LAjitRegularExpressionValidator regStartCheck;
        protected System.Web.UI.HtmlControls.HtmlTableRow trEntryVendor;
        protected System.Web.UI.WebControls.Label lblEntryVendor;
        protected LAjitControls.LAjitDropDownList ddlEntryVendor;
        protected LAjitControls.LAjitRequiredFieldValidator reqEntryVendor;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDescription;
        protected System.Web.UI.WebControls.Label lblDescription;
        protected LAjitControls.LAjitTextBox txtDescription;
        protected LAjitControls.LAjitRequiredFieldValidator reqDescription;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAccountName;
        protected System.Web.UI.WebControls.Label lblAccountName;
        protected LAjitControls.LAjitTextBox txtAccountName;
        protected LAjitControls.LAjitRequiredFieldValidator reqAccountName;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAmountEntered;
        protected System.Web.UI.WebControls.Label lblAmountEntered;
        protected LAjitControls.LAjitTextBox txtAmountEntered;
        protected LAjitControls.LAjitRequiredFieldValidator reqAmountEntered;
        protected LAjitControls.LAjitRegularExpressionValidator regAmountEntered;
        protected System.Web.UI.HtmlControls.HtmlTableRow trControlTotal;
        protected System.Web.UI.WebControls.Label lblControlTotal;
        protected LAjitControls.LAjitTextBox txtControlTotal;
        protected LAjitControls.LAjitRequiredFieldValidator reqControlTotal;
        protected LAjitControls.LAjitRegularExpressionValidator regControlTotal;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCGITotal;
        protected System.Web.UI.WebControls.Label lblCGITotal;
        protected LAjitControls.LAjitTextBox txtCGITotal;
        protected LAjitControls.LAjitRequiredFieldValidator reqCGITotal;
        protected LAjitControls.LAjitRegularExpressionValidator regCGITotal;
        protected LAjitDev.UserControls.ChildGridView CGVUC;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
    }
}
