//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Payables {
    
    public partial class VoidCheckHistory {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlBtnsContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTable tblEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trEntryBank_JournalDoc;
        protected System.Web.UI.WebControls.Label lblEntryBank_JournalDoc;
        protected LAjitControls.LAjitDropDownList ddlEntryBank_JournalDoc;
        protected LAjitControls.LAjitRequiredFieldValidator reqEntryBank_JournalDoc;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCheckNumber_JournalDoc;
        protected System.Web.UI.WebControls.Label lblCheckNumber_JournalDoc;
        protected LAjitControls.LAjitTextBox txtCheckNumber_JournalDoc;
        protected LAjitControls.LAjitRequiredFieldValidator reqCheckNumber_JournalDoc;
        protected System.Web.UI.HtmlControls.HtmlTableRow trVendor_JournalDoc;
        protected System.Web.UI.WebControls.Label lblVendor_JournalDoc;
        protected LAjitControls.LAjitTextBox txtVendor_JournalDoc;
        protected LAjitControls.LAjitRequiredFieldValidator reqVendor_JournalDoc;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPaymentDate_JournalDoc;
        protected System.Web.UI.WebControls.Label lblPaymentDate_JournalDoc;
        protected LAjitControls.LAjitTextBox txtPaymentDate_JournalDoc;
        protected LAjitControls.LAjitRequiredFieldValidator reqPaymentDate_JournalDoc;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCheckMessage_JournalDoc;
        protected LAjitControls.LAjitLabel lblCheckMessage_JournalDoc_Value;
        protected System.Web.UI.HtmlControls.HtmlTableRow trControlTotal;
        protected System.Web.UI.WebControls.Label lblControlTotal;
        protected LAjitControls.LAjitTextBox txtControlTotal;
        protected LAjitControls.LAjitRequiredFieldValidator reqControlTotal;
        protected LAjitControls.LAjitRegularExpressionValidator regControlTotal;
        protected System.Web.UI.WebControls.Label lblMemo;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSelectAPInvoiceType_JournalDoc;
        protected System.Web.UI.WebControls.Label lblSelectAPInvoiceType_JournalDoc;
        protected LAjitControls.LAjitDropDownList ddlSelectAPInvoiceType_JournalDoc;
        protected LAjitControls.LAjitRequiredFieldValidator reqSelectAPInvoiceType_JournalDoc;
        protected System.Web.UI.HtmlControls.HtmlTableRow trVoidDate_JournalDoc;
        protected System.Web.UI.WebControls.Label lblVoidDate_JournalDoc;
        protected LAjitControls.LAjitTextBox txtVoidDate_JournalDoc;
        protected LAjitControls.LAjitRequiredFieldValidator reqVoidDate_JournalDoc;
        protected System.Web.UI.HtmlControls.HtmlTableRow trVoidOrigDate_JournalDoc;
        protected System.Web.UI.WebControls.Label lblVoidOrigDate_JournalDoc;
        protected LAjitControls.LAjitCheckBox chkVoidOrigDate_JournalDoc;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSelectBatch_JournalDoc;
        protected System.Web.UI.WebControls.Label lblSelectBatch_JournalDoc;
        protected LAjitControls.LAjitDropDownList ddlSelectBatch_JournalDoc;
        protected LAjitControls.LAjitRequiredFieldValidator reqSelectBatch_JournalDoc;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCurrencyTypeCompany;
        protected System.Web.UI.WebControls.Label lblCurrencyTypeCompany;
        protected LAjitControls.LAjitDropDownList ddlCurrencyTypeCompany;
        protected LAjitControls.LAjitRequiredFieldValidator reqCurrencyTypeCompany;
        protected System.Web.UI.HtmlControls.HtmlTableRow trInvDate;
        protected System.Web.UI.WebControls.Label lblInvDate;
        protected LAjitControls.LAjitTextBox txtInvDate;
        protected LAjitControls.LAjitRequiredFieldValidator reqInvDate;
        protected System.Web.UI.HtmlControls.HtmlTableRow trInvNumber;
        protected System.Web.UI.WebControls.Label lblInvNumber;
        protected LAjitControls.LAjitTextBox txtInvNumber;
        protected LAjitControls.LAjitRequiredFieldValidator reqInvNumber;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPOReference_JournalDoc;
        protected System.Web.UI.WebControls.Label lblPOReference_JournalDoc;
        protected LAjitControls.LAjitTextBox txtPOReference_JournalDoc;
        protected LAjitControls.LAjitRequiredFieldValidator reqPOReference_JournalDoc;
        protected System.Web.UI.HtmlControls.HtmlTableRow trVendor;
        protected System.Web.UI.WebControls.Label lblVendor;
        protected LAjitControls.LAjitTextBox txtVendor;
        protected LAjitControls.LAjitRequiredFieldValidator reqVendor;
        protected System.Web.UI.HtmlControls.HtmlTableRow trJournalRef;
        protected System.Web.UI.WebControls.Label lblJournalRef;
        protected LAjitControls.LAjitTextBox txtJournalRef;
        protected LAjitControls.LAjitRequiredFieldValidator reqJournalRef;
        protected System.Web.UI.WebControls.Panel pnlCPGV2Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcHeaderAccountingItem;
        protected System.Web.UI.WebControls.Panel pnlCPGV2TitleContent;
        protected System.Web.UI.WebControls.Panel pnlGVBranch;
        protected System.Web.UI.WebControls.GridView grdVwAccountingItem;
        protected System.Web.UI.WebControls.Table tblOperationLinks;
        protected System.Web.UI.WebControls.LinkButton lnkBtnAddNewRow;
        protected System.Web.UI.WebControls.LinkButton lnkBtnDeleteRow;
        protected System.Web.UI.WebControls.LinkButton lnkBtnToggle;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
    }
}
