//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.UserControls {
    
    public partial class ButtonsUserControl {
        protected System.Web.UI.UpdatePanel updtPnlGrdVw;
        protected System.Web.UI.WebControls.Panel pnlBtnsUC;
        protected System.Web.UI.HtmlControls.HtmlTableRow trImgbtnAdd;
        protected LAjitControls.LAjitImageButton imgbtnAdd;
        protected System.Web.UI.HtmlControls.HtmlTableRow trImgbtnClone;
        protected LAjitControls.LAjitImageButton imgbtnClone;
        protected System.Web.UI.HtmlControls.HtmlTableRow trImgbtnModify;
        protected LAjitControls.LAjitImageButton imgbtnModify;
        protected System.Web.UI.HtmlControls.HtmlTableRow trImgbtnDelete;
        protected LAjitControls.LAjitImageButton imgbtnDelete;
        protected System.Web.UI.HtmlControls.HtmlTableRow trImgbtnFind;
        protected LAjitControls.LAjitImageButton imgbtnFind;
        protected System.Web.UI.HtmlControls.HtmlTableRow trImgbtnPrint;
        protected System.Web.UI.WebControls.Panel pnlMenuPrint;
        protected LAjitControls.LAjitImageButton imgbtnPrint;
        protected System.Web.UI.HtmlControls.HtmlTableRow trImgbtnNote;
        protected System.Web.UI.WebControls.ImageButton imgbtnNote;
        protected System.Web.UI.HtmlControls.HtmlTableRow trImgbtnSecure;
        protected System.Web.UI.WebControls.ImageButton imgbtnSecure;
        protected System.Web.UI.HtmlControls.HtmlTableRow trImgbtnAttachment;
        protected System.Web.UI.WebControls.ImageButton imgbtnAttachment;
        protected System.Web.UI.WebControls.HiddenField hdnCnfmSbmt;
        protected System.Web.UI.WebControls.HiddenField hdnRwToBeModified;
        protected System.Web.UI.WebControls.HiddenField hdnSelected;
        protected System.Web.UI.WebControls.HiddenField parentBPInfo;
        protected System.Web.UI.WebControls.HiddenField hdnBranchColsXML;
        protected System.Web.UI.WebControls.HiddenField hdnFldBPInfo;
        protected System.Web.UI.WebControls.HiddenField hdnFldReportName;
        protected System.Web.UI.WebControls.HiddenField hdnNeedToConfirmExit;
        protected System.Web.UI.WebControls.HiddenField hdnFormInfo;
        protected System.Web.UI.WebControls.HiddenField hdnBPIconBPEINFO;
        protected System.Web.UI.WebControls.HiddenField hdnBranchXML;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hdnNavBPInfo;
        protected System.Web.UI.WebControls.HiddenField hdnGVBPEINFO;
        protected System.Web.UI.WebControls.HiddenField hdnPrintInfo;
        protected System.Web.UI.WebControls.HiddenField hdnAutoFillBPEINFO;
        protected System.Web.UI.WebControls.HiddenField hdnChartBPEINFO;
        protected System.Web.UI.WebControls.HiddenField hdnParentColNode;
        protected System.Web.UI.WebControls.HiddenField hdnCurrAction;
        protected System.Web.UI.WebControls.HiddenField hdnTimerValue;
        protected System.Web.UI.WebControls.HiddenField hdnSubmitstatus;
    }
}
