//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.UserControls {
    
    public partial class ChildGridView {
        protected System.Web.UI.UpdatePanel upCGVUC;
        protected System.Web.UI.HtmlControls.HtmlTable tblCGVTop;
        protected System.Web.UI.WebControls.Panel pnlTitle;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcStartSpacer;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcExpandImage;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcHeader;
        protected System.Web.UI.WebControls.Panel pnlTitleTarget;
        protected System.Web.UI.WebControls.Panel pnlGVBranch;
        protected System.Web.UI.WebControls.GridView grdVwBranch;
        protected System.Web.UI.WebControls.Table tblBPCLinks;
        protected System.Web.UI.WebControls.Table tblOpLinks;
        protected System.Web.UI.WebControls.LinkButton lnkBtnAddRows;
        protected System.Web.UI.WebControls.TableCell addSeperator;
        protected System.Web.UI.WebControls.LinkButton lnkBtnDeleteRow;
        protected System.Web.UI.WebControls.TableCell deleteSeperator;
        protected System.Web.UI.WebControls.LinkButton lnkBtnToggle;
        protected System.Web.UI.WebControls.TableCell toggleSeperator;
        protected System.Web.UI.WebControls.LinkButton lnkBtnCopy;
        protected System.Web.UI.WebControls.TableCell copySeperator;
        protected System.Web.UI.WebControls.LinkButton lnkBtnPaste;
        protected System.Web.UI.WebControls.Table tblAmounts;
        protected System.Web.UI.WebControls.HiddenField hdnRowsToDelete;
        protected System.Web.UI.WebControls.HiddenField hdnRowCount;
        protected System.Web.UI.WebControls.HiddenField hdnAddedRows;
        protected System.Web.UI.WebControls.HiddenField hdnRowsToDisplay;
        protected System.Web.UI.WebControls.HiddenField hdnBranchNodeName;
        protected System.Web.UI.WebControls.HiddenField hdnModRows;
        protected System.Web.UI.WebControls.HiddenField hdnAmounts;
        protected System.Web.UI.WebControls.HiddenField hdnIsPaging;
        protected System.Web.UI.WebControls.HiddenField hdnJobCOADefault;
    }
}
