//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev {
    
    public partial class ParentChildGV {
        protected System.Web.UI.UpdatePanel updtPnlGrdVw;
        protected System.Web.UI.HtmlControls.HtmlTableRow trTitle;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcGridTitle;
        protected System.Web.UI.WebControls.DataGrid grdVwContents;
        protected System.Web.UI.WebControls.Panel pnlPagingCtrls;
        protected System.Web.UI.WebControls.LinkButton lbtnFirst;
        protected System.Web.UI.WebControls.LinkButton lbtnPrevious;
        protected System.Web.UI.WebControls.Label lblPageStatus;
        protected System.Web.UI.WebControls.LinkButton lbtnNext;
        protected System.Web.UI.WebControls.LinkButton lbtnLast;
        protected System.Web.UI.WebControls.Label lblPageNo;
        protected System.Web.UI.WebControls.DropDownList ddlPages;
        protected System.Web.UI.WebControls.Panel pnlPrint;
        protected System.Web.UI.WebControls.ImageButton imgBtnPrint;
        protected System.Web.UI.WebControls.ImageButton imgBtnChart;
        protected System.Web.UI.WebControls.ImageButton imgBtnPDF;
        protected System.Web.UI.WebControls.ImageButton imgBtnExcel;
        protected System.Web.UI.WebControls.ImageButton imgBtnHtml;
        protected System.Web.UI.WebControls.ImageButton imgBtnMSWord;
        protected System.Web.UI.WebControls.ImageButton imgBtnEmailPDF;
        protected System.Web.UI.WebControls.Label lblXAxis;
        protected LAjitControls.LAjitDropDownList ddlXAxis;
        protected System.Web.UI.WebControls.Label lblYAxis;
        protected LAjitControls.LAjitDropDownList ddlYAxis;
        protected System.Web.UI.WebControls.Label lblEmailIDs;
        protected LAjitControls.LAjitTextBox txtEmailing;
        protected System.Web.UI.WebControls.RadioButton radCurrent1;
        protected System.Web.UI.WebControls.RadioButton radAll1;
        protected System.Web.UI.WebControls.HiddenField hdnMainViewState;
        protected System.Web.UI.WebControls.HiddenField hdnMaxPages;
        protected System.Web.UI.WebControls.HiddenField hdnCurrPageNo;
        protected System.Web.UI.WebControls.HiddenField hdnGVTreeNodeName;
        protected System.Web.UI.WebControls.HiddenField hdnRowObject;
        protected System.Web.UI.WebControls.HiddenField hdnDefaultPageSize;
        protected System.Web.UI.WebControls.HiddenField hdnFormInfo;
        protected System.Web.UI.WebControls.HiddenField hdnGVBPEINFO;
        protected System.Web.UI.WebControls.HiddenField hdnSearchBPInfo;
        protected System.Web.UI.WebControls.HiddenField hdnPreviewInPopup;
    }
}
