//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Common {
    
    public partial class ChartViewer {
        protected System.Web.UI.HtmlControls.HtmlForm aspnetForm;
        protected System.Web.UI.ScriptManager ChartViewerScriptMngr;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow XYDDLEntryform;
        protected System.Web.UI.WebControls.Label lblXAxis;
        protected System.Web.UI.WebControls.DropDownList ddlXAxis;
        protected System.Web.UI.WebControls.Label lblYAxis;
        protected System.Web.UI.WebControls.DropDownList ddlYAxis;
        protected System.Web.UI.WebControls.Label lblChartType;
        protected System.Web.UI.WebControls.DropDownList ddlChartTypes;
        protected System.Web.UI.WebControls.ImageButton btnSubmit;
        protected System.Web.UI.WebControls.Panel pnlChart;
        protected System.Web.UI.UserControl CUC;
        protected System.Web.UI.WebControls.Panel pnlExportPDF;
        protected System.Web.UI.WebControls.Label lblPDF;
        protected System.Web.UI.WebControls.ImageButton imgbtnExportPDF;
        protected System.Web.UI.WebControls.Panel pnlDataError;
        protected System.Web.UI.WebControls.Label lblErrMsg;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.WebControls.HiddenField hdnChartCFN;
        protected System.Web.UI.WebControls.Panel pnlPagePopUp;
        protected System.Web.UI.WebControls.LinkButton lnkBtnCloseIFrame;
    }
}
