//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Common {
    
    public partial class ChartView {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlBtnsContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.UserControl CUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trXaxisText;
        protected System.Web.UI.WebControls.Label lblXaxisText;
        protected LAjitControls.LAjitTextBox txtXaxisText;
        protected LAjitControls.LAjitRequiredFieldValidator reqXaxisText;
        protected System.Web.UI.HtmlControls.HtmlTableRow trXaxisValue;
        protected System.Web.UI.WebControls.Label lblXaxisValue;
        protected LAjitControls.LAjitTextBox txtXaxisValue;
        protected LAjitControls.LAjitRequiredFieldValidator reqXaxisValue;
        protected System.Web.UI.HtmlControls.HtmlTableRow trYaxisText;
        protected System.Web.UI.WebControls.Label lblYaxisText;
        protected LAjitControls.LAjitTextBox txtYaxisText;
        protected LAjitControls.LAjitRequiredFieldValidator reqYaxisText;
        protected System.Web.UI.HtmlControls.HtmlTableRow trYaxisValue;
        protected System.Web.UI.WebControls.Label lblYaxisValue;
        protected LAjitControls.LAjitTextBox txtYaxisValue;
        protected LAjitControls.LAjitRequiredFieldValidator reqYaxisValue;
        protected System.Web.UI.HtmlControls.HtmlTableRow trXaxisColor;
        protected System.Web.UI.WebControls.Label lblXaxisColor;
        protected LAjitControls.LAjitTextBox txtXaxisColor;
        protected LAjitControls.LAjitRequiredFieldValidator reqXaxisColor;
        protected System.Web.UI.HtmlControls.HtmlTableRow trXaxisFont;
        protected System.Web.UI.WebControls.Label lblXaxisFont;
        protected LAjitControls.LAjitTextBox txtXaxisFont;
        protected LAjitControls.LAjitRequiredFieldValidator reqXaxisFont;
        protected System.Web.UI.HtmlControls.HtmlTableRow trYaxisColor;
        protected System.Web.UI.WebControls.Label lblYaxisColor;
        protected LAjitControls.LAjitTextBox txtYaxisColor;
        protected LAjitControls.LAjitRequiredFieldValidator reqYaxisColor;
        protected System.Web.UI.HtmlControls.HtmlTableRow trYaxisFont;
        protected System.Web.UI.WebControls.Label lblYaxisFont;
        protected LAjitControls.LAjitTextBox txtYaxisFont;
        protected LAjitControls.LAjitRequiredFieldValidator reqYaxisFont;
        protected System.Web.UI.HtmlControls.HtmlTableRow trIsLegendDisplayed;
        protected System.Web.UI.WebControls.Label lblIsLegendDisplayed;
        protected LAjitControls.LAjitTextBox txtIsLegendDisplayed;
        protected LAjitControls.LAjitRequiredFieldValidator reqIsLegendDisplayed;
        protected System.Web.UI.HtmlControls.HtmlTableRow trIsChartNameDisplayed;
        protected System.Web.UI.WebControls.Label lblIsChartNameDisplayed;
        protected LAjitControls.LAjitTextBox txtIsChartNameDisplayed;
        protected LAjitControls.LAjitRequiredFieldValidator reqIsChartNameDisplayed;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidXML;
    }
}
