//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Common {
    
    public partial class ContentError {
        protected System.Web.UI.HtmlControls.HtmlForm ContentErrorForm;
        protected System.Web.UI.WebControls.LinkButton btnExit;
    }
}
