//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev {
    
    public partial class DashBoard {
        protected System.Web.UI.WebControls.HiddenField hdnFormInfo;
        protected System.Web.UI.WebControls.HiddenField parentBPInfo;
        protected System.Web.UI.WebControls.Panel pnlExpView;
        protected System.Web.UI.WebControls.Panel pnlExpViewContent;
        protected System.Web.UI.WebControls.Table tblMainContents;
        protected System.Web.UI.WebControls.Panel pnlCPGV2;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV2;
        protected System.Web.UI.WebControls.Panel pnlCPGV2Content;
        protected System.Web.UI.WebControls.GridView grdvCenterPanel2;
        protected System.Web.UI.WebControls.LinkButton lnkBtnCPGV2FV;
        protected System.Web.UI.WebControls.Panel pnlCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Content;
        protected System.Web.UI.WebControls.GridView grdvCenterPanel1;
        protected System.Web.UI.WebControls.LinkButton lnkBtnCPGV1FV;
        protected System.Web.UI.WebControls.Panel pnlCPGraphics;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGraphics;
        protected System.Web.UI.WebControls.Panel pnlCPGraphicsContent;
        protected System.Web.UI.WebControls.Table tblCPGraphics;
        protected LAjitDev.UserControls.ChartUserControl CUC1;
        protected System.Web.UI.WebControls.Panel pnlRPGV1;
        protected System.Web.UI.WebControls.Panel pnlRPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcRPGV1;
        protected System.Web.UI.WebControls.Panel pnlRPGV1Content;
        protected System.Web.UI.WebControls.GridView grdVwRightPanel1;
        protected System.Web.UI.WebControls.LinkButton lnkBtnRPGV1FV;
        protected System.Web.UI.WebControls.Panel pnlRPGV2;
        protected System.Web.UI.WebControls.Panel pnlRPGV2Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcRPGV2;
        protected System.Web.UI.WebControls.Panel pnlRPGV2Content;
        protected System.Web.UI.WebControls.GridView grdVwRightPanel2;
        protected System.Web.UI.WebControls.LinkButton lnkBtnRPGV2FV;
        protected System.Web.UI.WebControls.Panel pnlRPGV3;
        protected System.Web.UI.WebControls.Panel pnlRPGV3Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcRPGV3;
        protected System.Web.UI.WebControls.Panel pnlRPGV3Content;
        protected System.Web.UI.WebControls.GridView grdVwRightPanel3;
        protected System.Web.UI.WebControls.LinkButton lnkBtnRPGV3FV;
        protected System.Web.UI.WebControls.Panel pnlRPGV4;
        protected System.Web.UI.WebControls.Panel pnlRPGV4Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcRPGV4;
        protected System.Web.UI.WebControls.Panel pnlRPGV4Content;
        protected System.Web.UI.WebControls.GridView grdVwRightPanel4;
        protected System.Web.UI.WebControls.LinkButton lnkBtnRPGV4FV;
        protected System.Web.UI.WebControls.Panel pnlRPGV5;
        protected System.Web.UI.WebControls.Panel pnlRPGV5Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcRPGV5;
        protected System.Web.UI.WebControls.Panel pnlRPGV5Content;
        protected System.Web.UI.WebControls.Literal litRss;
        protected System.Web.UI.UpdatePanel updtPnlRssTimer;
        protected System.Web.UI.Timer timerRSSUpdater;
    }
}
