//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Common {
    
    public partial class DetailedView {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.ScriptManager ScriptManager1;
        protected LAjitDev.GridViewControl ucGridView;
        protected System.Web.UI.HtmlControls.HtmlInputHidden ctl00_hdnThemeName;
        protected System.Web.UI.WebControls.HiddenField hdnFindBPGID;
        protected System.Web.UI.WebControls.Panel pnlPagePopUp;
        protected System.Web.UI.WebControls.LinkButton lnkBtnCloseIFrame;
    }
}
