//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Common {
    
    public partial class GenProcessEngine {
        protected System.Web.UI.WebControls.Panel pnlBtns;
        protected LAjitControls.JQGridView.JQGridView jqGrid;
        protected System.Web.UI.UpdatePanel upReportsHoverPanel;
        protected System.Web.UI.WebControls.Label lblXAxis;
        protected LAjitControls.LAjitDropDownList ddlXAxis;
        protected System.Web.UI.WebControls.Label lblYAxis;
        protected LAjitControls.LAjitDropDownList ddlYAxis;
        protected System.Web.UI.WebControls.Label lblEmailIDs;
        protected LAjitControls.LAjitTextBox txtEmailing;
        protected System.Web.UI.WebControls.RadioButton radCurrent1;
        protected System.Web.UI.WebControls.RadioButton radAll1;
        protected System.Web.UI.WebControls.HiddenField hdnFormLvlLinks;
        protected System.Web.UI.WebControls.HiddenField hdnFormInfo;
        protected System.Web.UI.WebControls.HiddenField hdnSOXApprStatus;
        protected System.Web.UI.WebControls.HiddenField hdnBPInfo;
        protected System.Web.UI.WebControls.HiddenField hdnPreviewInPopup;
        protected System.Web.UI.WebControls.HiddenField hdnNodeRow;
        protected System.Web.UI.WebControls.HiddenField hdnSelectedCols;
        protected System.Web.UI.WebControls.HiddenField hdnJobCOADefault;
    }
}
