//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Common {
    
    public partial class Help {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTable tblEntryForm;
        protected System.Web.UI.WebControls.ImageButton imgbtnSearch;
        protected LAjitControls.LAjitTextBox txthelpcatalog;
        protected System.Web.UI.WebControls.ImageButton imgbtnGo;
        protected System.Web.UI.HtmlControls.HtmlImage imghelplogo;
        protected System.Web.UI.WebControls.Panel pnlHelpTable;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.WebControls.HiddenField hdnAutoFillBPGID;
    }
}
