//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Common {
    
    public partial class AuthorHelp {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlBtnsContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryFormTitle;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcEntryFormAuto;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSoxApprovedStatus;
        protected LAjitControls.LAjitImageButton imgbtnIsApproved;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDisplaySeq;
        protected System.Web.UI.WebControls.Label lblDisplaySeq;
        protected LAjitControls.LAjitTextBox txtDisplaySeq;
        protected LAjitControls.LAjitRequiredFieldValidator reqDisplaySeq;
        protected System.Web.UI.HtmlControls.HtmlTableRow trHelpCatalog;
        protected System.Web.UI.WebControls.Label lblHelpCatalog;
        protected LAjitControls.LAjitTextBox txtHelpCatalog;
        protected LAjitControls.LAjitRequiredFieldValidator reqHelpCatalog;
        protected System.Web.UI.WebControls.Label lblHelpFileCaption;
        protected LAjitControls.LAjitDropDownList ddlHelpFileCaption;
        protected LAjitControls.LAjitRequiredFieldValidator reqHelpFileCaption;
        protected System.Web.UI.HtmlControls.HtmlTableRow trHelpCaption;
        protected System.Web.UI.WebControls.Label lblHelpCaption;
        protected LAjitControls.LAjitTextBox txtHelpCaption;
        protected LAjitControls.LAjitRequiredFieldValidator reqHelpCaption;
        protected System.Web.UI.HtmlControls.HtmlTableRow trHelpText;
        protected System.Web.UI.WebControls.Label lblHelpText;
        protected LAjitControls.LAjitTextBox txtHelpText;
        protected LAjitControls.LAjitRequiredFieldValidator reqHelpText;
        protected System.Web.UI.HtmlControls.HtmlTableRow trHelpFile;
        protected System.Web.UI.WebControls.Label lblHelpFile;
        protected System.Web.UI.WebControls.FileUpload txtFileAttachment;
        protected LAjitControls.LAjitTextBox txtHelpFile;
        protected LAjitControls.LAjitRequiredFieldValidator reqHelpFile;
        protected System.Web.UI.WebControls.Label lblHelpFileType;
        protected LAjitControls.LAjitDropDownList ddlHelpFileType;
        protected LAjitControls.LAjitRequiredFieldValidator reqHelpFileType;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
    }
}
