//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Financials {
    
    public partial class ModificationRequest {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlBtnsContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trModReqestID;
        protected System.Web.UI.WebControls.Label lblModReqestID;
        protected LAjitControls.LAjitTextBox txtModReqestID;
        protected LAjitControls.LAjitRequiredFieldValidator reqModReqestID;
        protected System.Web.UI.HtmlControls.HtmlTableRow trRequestOwner;
        protected System.Web.UI.WebControls.Label lblRequestOwner;
        protected LAjitControls.LAjitTextBox txtRequestOwner;
        protected LAjitControls.LAjitRequiredFieldValidator reqRequestOwner;
        protected System.Web.UI.HtmlControls.HtmlTableRow trBprocess;
        protected System.Web.UI.WebControls.Label lblBprocess;
        protected LAjitControls.LAjitTextBox txtBprocess;
        protected LAjitControls.LAjitRequiredFieldValidator reqBprocess;
        protected System.Web.UI.HtmlControls.HtmlTableRow trModificationStatus;
        protected System.Web.UI.WebControls.Label lblModificationStatus;
        protected LAjitControls.LAjitDropDownList ddlModificationStatus;
        protected LAjitControls.LAjitRequiredFieldValidator reqModificationStatus;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCreatedBy;
        protected System.Web.UI.WebControls.Label lblCreatedBy;
        protected LAjitControls.LAjitDropDownList ddlCreatedBy;
        protected LAjitControls.LAjitRequiredFieldValidator reqCreatedBy;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDescription;
        protected System.Web.UI.WebControls.Label lblDescription;
        protected LAjitControls.LAjitTextBox txtDescription;
        protected LAjitControls.LAjitRequiredFieldValidator reqDescription;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPrioritySeq;
        protected System.Web.UI.WebControls.Label lblPrioritySeq;
        protected LAjitControls.LAjitTextBox txtPrioritySeq;
        protected LAjitControls.LAjitRequiredFieldValidator reqPrioritySeq;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDeveloperType;
        protected System.Web.UI.WebControls.Label lblDeveloperType;
        protected LAjitControls.LAjitDropDownList ddlDeveloperType;
        protected LAjitControls.LAjitRequiredFieldValidator reqDeveloperType;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDeveloper2Type;
        protected System.Web.UI.WebControls.Label lblDeveloper2Type;
        protected LAjitControls.LAjitDropDownList ddlDeveloper2Type;
        protected LAjitControls.LAjitRequiredFieldValidator reqDeveloper2Type;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDeveloperNotes;
        protected System.Web.UI.WebControls.Label lblDeveloperNotes;
        protected LAjitControls.LAjitTextBox txtDeveloperNotes;
        protected LAjitControls.LAjitRequiredFieldValidator reqDeveloperNotes;
        protected System.Web.UI.HtmlControls.HtmlTableRow trQANotes;
        protected System.Web.UI.WebControls.Label lblQANotes;
        protected LAjitControls.LAjitTextBox txtQANotes;
        protected LAjitControls.LAjitRequiredFieldValidator reqQANotes;
        protected System.Web.UI.HtmlControls.HtmlTableRow trUser2Type;
        protected System.Web.UI.WebControls.Label lblUser2Type;
        protected LAjitControls.LAjitDropDownList ddlUser2Type;
        protected LAjitControls.LAjitRequiredFieldValidator reqUser2Type;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDateCreated;
        protected System.Web.UI.WebControls.Label lblDateCreated;
        protected LAjitControls.LAjitTextBox txtDateCreated;
        protected System.Web.UI.HtmlControls.HtmlTableRow trModificationSeverity;
        protected System.Web.UI.WebControls.Label lblModificationSeverity;
        protected LAjitControls.LAjitDropDownList ddlModificationSeverity;
        protected LAjitControls.LAjitRequiredFieldValidator reqModificationSeverity;
        protected System.Web.UI.HtmlControls.HtmlTableRow trModificationType;
        protected System.Web.UI.WebControls.Label lblModificationType;
        protected LAjitControls.LAjitDropDownList ddlModificationType;
        protected LAjitControls.LAjitRequiredFieldValidator reqModificationType;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDatedAssigned;
        protected System.Web.UI.WebControls.Label lblDatedAssigned;
        protected LAjitControls.LAjitTextBox txtDatedAssigned;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDateComplete;
        protected System.Web.UI.WebControls.Label lblDateComplete;
        protected LAjitControls.LAjitTextBox txtDateComplete;
        protected System.Web.UI.HtmlControls.HtmlTableRow trReviseDate;
        protected System.Web.UI.WebControls.Label lblReviseDate;
        protected LAjitControls.LAjitTextBox txtReviseDate;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divChecks;
        protected System.Web.UI.WebControls.Label lblNotify;
        protected System.Web.UI.HtmlControls.HtmlInputCheckBox chkOwner;
        protected System.Web.UI.HtmlControls.HtmlInputCheckBox chkRevisedBy;
        protected System.Web.UI.HtmlControls.HtmlInputCheckBox chkDevManager;
        protected System.Web.UI.HtmlControls.HtmlInputCheckBox chkAssignedToDev;
        protected System.Web.UI.HtmlControls.HtmlInputCheckBox chkAssignedToQA;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
    }
}
