//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev {
    
    public partial class PreDashBoard {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected System.Web.UI.WebControls.Table entyTbl;
        protected System.Web.UI.WebControls.Table cmpnyTbl;
        protected System.Web.UI.WebControls.Table rlTbl;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hiddenEntyStrID;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hiddenCmpnyStrID;
    }
}
