//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Common {
    
    public partial class ProcessEngine {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTable tblEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trReportLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdReportLinks;
        protected System.Web.UI.WebControls.Panel pnlReport;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDescription;
        protected System.Web.UI.WebControls.Label lblDescriptionValue;
        protected System.Web.UI.HtmlControls.HtmlTableRow Tr1;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenericSelect1;
        protected System.Web.UI.WebControls.Label lblGenericSelect1;
        protected LAjitControls.LAjitDropDownList ddlGenericSelect1;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenericSelect2;
        protected System.Web.UI.WebControls.Label lblGenericSelect2;
        protected LAjitControls.LAjitDropDownList ddlGenericSelect2;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenericSelect3;
        protected System.Web.UI.WebControls.Label lblGenericSelect3;
        protected LAjitControls.LAjitDropDownList ddlGenericSelect3;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenericSelect4;
        protected System.Web.UI.WebControls.Label lblGenericSelect4;
        protected LAjitControls.LAjitDropDownList ddlGenericSelect4;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenericSelect5;
        protected System.Web.UI.WebControls.Label lblGenericSelect5;
        protected LAjitControls.LAjitDropDownList ddlGenericSelect5;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenSDate1;
        protected System.Web.UI.WebControls.Label lblGenSDate1;
        protected LAjitControls.LAjitTextBox txtGenSDate1;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenEDate1;
        protected System.Web.UI.WebControls.Label lblGenEDate1;
        protected LAjitControls.LAjitTextBox txtGenEDate1;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenSDate2;
        protected System.Web.UI.WebControls.Label lblGenSDate2;
        protected LAjitControls.LAjitTextBox txtGenSDate2;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenEDate2;
        protected System.Web.UI.WebControls.Label lblGenEDate2;
        protected LAjitControls.LAjitTextBox txtGenEDate2;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenSDate3;
        protected System.Web.UI.WebControls.Label lblGenSDate3;
        protected LAjitControls.LAjitTextBox txtGenSDate3;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenEDate3;
        protected System.Web.UI.WebControls.Label lblGenEDate3;
        protected LAjitControls.LAjitTextBox txtGenEDate3;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenSRange1;
        protected System.Web.UI.WebControls.Label lblGenSRange1;
        protected LAjitControls.LAjitTextBox txtGenSRange1;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenERange1;
        protected System.Web.UI.WebControls.Label lblGenERange1;
        protected LAjitControls.LAjitTextBox txtGenERange1;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenSRange2;
        protected System.Web.UI.WebControls.Label lblGenSRange2;
        protected LAjitControls.LAjitTextBox txtGenSRange2;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenERange2;
        protected System.Web.UI.WebControls.Label lblGenERange2;
        protected LAjitControls.LAjitTextBox txtGenERange2;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenSRange3;
        protected System.Web.UI.WebControls.Label lblGenSRange3;
        protected LAjitControls.LAjitTextBox txtGenSRange3;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenERange3;
        protected System.Web.UI.WebControls.Label lblGenERange3;
        protected LAjitControls.LAjitTextBox txtGenERange3;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenSelect1;
        protected System.Web.UI.WebControls.Label lblGenSelect1;
        protected LAjitControls.LAjitCheckBox chkGenSelect1;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenSelect2;
        protected System.Web.UI.WebControls.Label lblGenSelect2;
        protected LAjitControls.LAjitCheckBox chkGenSelect2;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenSelect3;
        protected System.Web.UI.WebControls.Label lblGenSelect3;
        protected LAjitControls.LAjitCheckBox chkGenSelect3;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenSelect4;
        protected System.Web.UI.WebControls.Label lblGenSelect4;
        protected LAjitControls.LAjitCheckBox chkGenSelect4;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGenSelect5;
        protected System.Web.UI.WebControls.Label lblGenSelect5;
        protected LAjitControls.LAjitCheckBox chkGenSelect5;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.WebControls.Panel pnlProcessEngine;
        protected System.Web.UI.WebControls.Label lblStatus;
        protected System.Web.UI.UpdatePanel UpdPnlPrint;
        protected System.Web.UI.WebControls.Panel pnlPrint;
        protected System.Web.UI.WebControls.HiddenField parentBPInfo;
        protected System.Web.UI.WebControls.HiddenField hdnGVBPEINFO;
        protected System.Web.UI.WebControls.HiddenField hdnControls;
        protected System.Web.UI.WebControls.HiddenField hdnRwToBeModified;
    }
}
