//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Common {
    
    public partial class SetCompany {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlEntryFormTitle;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcEntryFormAuto;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTable tblEntryForm;
        protected System.Web.UI.WebControls.Label lblCompany;
        protected LAjitControls.LAjitDropDownList ddlEntity;
        protected System.Web.UI.WebControls.Label lblConfirm;
        protected System.Web.UI.WebControls.ImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidChecked;
        protected System.Web.UI.WebControls.HiddenField parentBPInfo;
        protected System.Web.UI.WebControls.HiddenField ParentGVDataXML;
        protected System.Web.UI.WebControls.HiddenField hdnFldBPInfo;
        protected System.Web.UI.WebControls.HiddenField hdnFldBPOut;
        protected System.Web.UI.WebControls.HiddenField hdnFldReportName;
        protected System.Web.UI.WebControls.HiddenField hdnNeedToConfirmExit;
        protected System.Web.UI.WebControls.HiddenField hdnBPIconBPEINFO;
    }
}
