//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Common {
    
    public partial class UploadAmex {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTable tblEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDescription;
        protected System.Web.UI.WebControls.Label lblDescriptionText;
        protected System.Web.UI.HtmlControls.HtmlTableRow trFileName;
        protected System.Web.UI.WebControls.Label lblFileName;
        protected System.Web.UI.WebControls.FileUpload FileAttachment;
        protected LAjitControls.LAjitRequiredFieldValidator reqFileName;
        protected System.Web.UI.WebControls.Panel pnlUpload;
        protected System.Web.UI.HtmlControls.HtmlTableRow trUploadOptionA;
        protected LAjitControls.LAjitCheckBox chkUploadOptionA;
        protected System.Web.UI.WebControls.Label lblUploadOptionA;
        protected System.Web.UI.HtmlControls.HtmlTableRow trUploadOptionB;
        protected LAjitControls.LAjitCheckBox chkUploadOptionB;
        protected System.Web.UI.WebControls.Label lblUploadOptionB;
        protected System.Web.UI.HtmlControls.HtmlTableRow trUploadOptionC;
        protected LAjitControls.LAjitCheckBox chkUploadOptionC;
        protected System.Web.UI.WebControls.Label lblUploadOptionC;
        protected System.Web.UI.WebControls.Label lblSecureCateogry;
        protected LAjitControls.LAjitDropDownList ddlSecureCategory;
        protected LAjitControls.LAjitRequiredFieldValidator reqSecureCategory;
        protected System.Web.UI.HtmlControls.HtmlTableRow trUploadOptionD;
        protected LAjitControls.LAjitCheckBox chkUploadOptionD;
        protected System.Web.UI.WebControls.Label lblUploadOptionD;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidChecked;
        protected System.Web.UI.WebControls.HiddenField parentBPInfo;
        protected System.Web.UI.WebControls.HiddenField ParentGVDataXML;
        protected System.Web.UI.WebControls.HiddenField hdnFldBPInfo;
        protected System.Web.UI.WebControls.HiddenField hdnFldBPOut;
        protected System.Web.UI.WebControls.HiddenField hdnFldReportName;
        protected System.Web.UI.WebControls.HiddenField hdnNeedToConfirmExit;
        protected System.Web.UI.WebControls.HiddenField hdnBPIconBPEINFO;
    }
}
