//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Reports {
    
    public partial class MyReports {
        protected System.Web.UI.HtmlControls.HtmlTable tblmain;
        protected System.Web.UI.WebControls.ImageButton imgbtnDelete;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrint;
        protected System.Web.UI.UpdatePanel UpdPnlReports;
        protected System.Web.UI.WebControls.Panel pnlMyReports;
        protected System.Web.UI.WebControls.GridView gvTree;
        protected System.Web.UI.WebControls.HiddenField hdnSelectedRows;
        protected System.Web.UI.WebControls.HiddenField hdnReportBPINFO;
        protected System.Web.UI.WebControls.Panel pnlPrint;
        protected System.Web.UI.WebControls.Panel pnlDrag;
        protected System.Web.UI.WebControls.RadioButton rbPDF;
        protected System.Web.UI.WebControls.RadioButton rbExcel;
        protected System.Web.UI.WebControls.RadioButton rbHTML;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrintOk;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrintCancel;
        protected System.Web.UI.WebControls.Panel pnlDelete;
        protected System.Web.UI.WebControls.Panel pnlDeleteDrag;
        protected System.Web.UI.UpdatePanel UpdpnlDelete;
        protected System.Web.UI.WebControls.ImageButton imgbtnDelOk;
        protected System.Web.UI.WebControls.ImageButton imgbtnDelCancel;
    }
}
