//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Financials {
    
    public partial class AccountFin {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlBtnsContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSoxApprovedStatus;
        protected LAjitControls.LAjitImageButton imgbtnIsApproved;
        protected System.Web.UI.HtmlControls.HtmlTableRow trNumberID;
        protected System.Web.UI.WebControls.Label lblNumberID;
        protected LAjitControls.LAjitTextBox txtNumberID;
        protected LAjitControls.LAjitRequiredFieldValidator reqtxtNumberID;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDescription;
        protected System.Web.UI.WebControls.Label lblDescription;
        protected LAjitControls.LAjitTextBox txtDescription;
        protected LAjitControls.LAjitRequiredFieldValidator reqTxtDescription;
        protected System.Web.UI.HtmlControls.HtmlTableRow trNoOverride;
        protected System.Web.UI.WebControls.Label lblNoOverride;
        protected LAjitControls.LAjitCheckBox chkNoOverride;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAccountType;
        protected System.Web.UI.WebControls.Label lblAccountType;
        protected LAjitControls.LAjitDropDownList ddlAccountType;
        protected LAjitControls.LAjitRequiredFieldValidator reqAccountType;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAllowJournal;
        protected System.Web.UI.WebControls.Label lblAllowJournal;
        protected LAjitControls.LAjitCheckBox chkAllowJournal;
        protected System.Web.UI.HtmlControls.HtmlTableRow trRollupAccount;
        protected System.Web.UI.WebControls.Label lblRollupAccount;
        protected LAjitControls.LAjitCheckBox chkRollupAccount;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCurrencyTypeCompany;
        protected System.Web.UI.WebControls.Label lblCurrencyTypeCompany;
        protected LAjitControls.LAjitDropDownList ddlCurrencyTypeCompany;
        protected LAjitControls.LAjitRequiredFieldValidator reqCurrencyTypeCompany;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDocConsol;
        protected System.Web.UI.WebControls.Label lblDocConsol;
        protected LAjitControls.LAjitDropDownList ddlDocConsol;
        protected LAjitControls.LAjitRequiredFieldValidator reqDocConsol;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
    }
}
