//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Financials {
    
    public partial class Batch {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlBtnsContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDescription;
        protected System.Web.UI.WebControls.Label lblDescription;
        protected LAjitControls.LAjitTextBox txtDescription;
        protected LAjitControls.LAjitRequiredFieldValidator reqDescription;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPostDate;
        protected System.Web.UI.WebControls.Label lblPostDate;
        protected LAjitControls.LAjitTextBox txtPostDate;
        protected LAjitControls.LAjitRequiredFieldValidator reqPostDate;
        protected System.Web.UI.HtmlControls.HtmlTableRow trControlTotal;
        protected System.Web.UI.WebControls.Label lblControlTotal;
        protected LAjitControls.LAjitTextBox txtControlTotal;
        protected LAjitControls.LAjitRegularExpressionValidator regControlTotal;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAmountEntered;
        protected System.Web.UI.WebControls.Label lblAmountEntered;
        protected LAjitControls.LAjitTextBox txtAmountEntered;
        protected LAjitControls.LAjitRequiredFieldValidator reqAmountEntered;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDefTransDate;
        protected System.Web.UI.WebControls.Label lblDefTransDate;
        protected LAjitControls.LAjitTextBox txtDefTransDate;
        protected LAjitControls.LAjitRequiredFieldValidator reqDefTransDate;
        protected System.Web.UI.HtmlControls.HtmlTableRow trIncrementMonth;
        protected System.Web.UI.WebControls.Label lblIncrementMonth;
        protected LAjitControls.LAjitTextBox txtIncrementMonth;
        protected LAjitControls.LAjitRequiredFieldValidator reqIncrementMonth;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDefCheckDate;
        protected System.Web.UI.WebControls.Label lblDefCheckDate;
        protected LAjitControls.LAjitTextBox txtDefCheckDate;
        protected LAjitControls.LAjitRequiredFieldValidator reqDefCheckDate;
        protected System.Web.UI.HtmlControls.HtmlTableRow trStdBatch;
        protected System.Web.UI.WebControls.Label lblStdBatch;
        protected LAjitControls.LAjitCheckBox chkStdBatch;
        protected System.Web.UI.HtmlControls.HtmlTableRow trBatchOwner;
        protected System.Web.UI.WebControls.Label lblBatchOwner;
        protected LAjitControls.LAjitTextBox txtBatchOwner;
        protected LAjitControls.LAjitRequiredFieldValidator reqBatchOwner;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
    }
}
