//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Financials {
    
    public partial class COA {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlBtnsContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSoxApprovedStatus;
        protected LAjitControls.LAjitImageButton imgbtnIsApproved;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDescription;
        protected System.Web.UI.WebControls.Label lblDescription;
        protected LAjitControls.LAjitTextBox txtDescription;
        protected LAjitControls.LAjitRequiredFieldValidator reqDescription;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCOAType;
        protected System.Web.UI.WebControls.Label lblCOAType;
        protected LAjitControls.LAjitDropDownList ddlCOAType;
        protected LAjitControls.LAjitRequiredFieldValidator reqCOAType;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGroupTotalAcctStd;
        protected System.Web.UI.WebControls.Label lblGroupTotalAcctStd;
        protected LAjitControls.LAjitDropDownList ddlGroupTotalAcctStd;
        protected LAjitControls.LAjitRequiredFieldValidator reqGroupTotalAcctStd;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGroupTotalCashFlow;
        protected System.Web.UI.WebControls.Label lblGroupTotalCashFlow;
        protected LAjitControls.LAjitDropDownList ddlGroupTotalCashFlow;
        protected LAjitControls.LAjitRequiredFieldValidator reqGroupTotalCashFlow;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAccountMask;
        protected System.Web.UI.WebControls.Label lblAccountMask;
        protected LAjitControls.LAjitDropDownList ddlAccountMask;
        protected LAjitControls.LAjitRequiredFieldValidator reqAccountMask;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAccountHeading;
        protected System.Web.UI.WebControls.Label lblAccountHeading;
        protected LAjitControls.LAjitDropDownList ddlAccountHeading;
        protected LAjitControls.LAjitRequiredFieldValidator reqAccountHeading;
        protected System.Web.UI.HtmlControls.HtmlTableRow trNumberReq;
        protected System.Web.UI.WebControls.Label lblNumberReq;
        protected LAjitControls.LAjitCheckBox chkNumberReq;
        protected System.Web.UI.HtmlControls.HtmlTableRow COAControl;
        protected System.Web.UI.WebControls.Label lblCOAControl;
        protected LAjitControls.LAjitCheckBox chkCOAControl;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
    }
}
