//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Financials {
    
    public partial class COAEntry {
        protected System.Web.UI.WebControls.ImageButton imgbtnAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnFind;
        protected System.Web.UI.WebControls.ImageButton imgbtnDelete;
        protected System.Web.UI.WebControls.ImageButton imgbtnUndo;
        protected System.Web.UI.WebControls.ImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnUpdate;
        protected System.Web.UI.WebControls.TextBox txtName;
        protected System.Web.UI.WebControls.DropDownList ddlDisplaySequence;
        protected System.Web.UI.WebControls.DropDownList ddlAccountNo;
        protected System.Web.UI.WebControls.DropDownList ddlFormatMask;
        protected System.Web.UI.WebControls.DropDownList ddlTypeofHeading;
        protected System.Web.UI.WebControls.DropDownList ddlStandarTotalGroup;
        protected System.Web.UI.WebControls.DropDownList ddlCashFlowGroup;
        protected System.Web.UI.WebControls.CheckBox chkAccountNumberRequired;
        protected System.Web.UI.WebControls.CheckBox chkIsNumeric;
        protected System.Web.UI.WebControls.CheckBox chkIsApproved;
        protected System.Web.UI.WebControls.CheckBox chkIsActive;
        protected System.Web.UI.WebControls.DropDownList ddlTypeOfInActiveStatus;
        protected System.Web.UI.WebControls.Button hiddenTargetControlForModalPopup;
        protected System.Web.UI.WebControls.Panel pnlDelete;
        protected System.Web.UI.WebControls.Button btnOk;
        protected System.Web.UI.WebControls.Button btnCancel;
    }
}
