//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Financials {
    
    public partial class CommercialBudget {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlBtnsContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTable tblEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSoxApprovedStatus;
        protected LAjitControls.LAjitImageButton imgbtnIsApproved;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDescription;
        protected System.Web.UI.WebControls.Label lblDescription;
        protected LAjitControls.LAjitTextBox txtDescription;
        protected LAjitControls.LAjitRequiredFieldValidator reqDescription;
        protected System.Web.UI.HtmlControls.HtmlTableRow trBudetType;
        protected System.Web.UI.WebControls.Label lblBudetType;
        protected LAjitControls.LAjitDropDownList ddlBudetType;
        protected LAjitControls.LAjitRequiredFieldValidator reqBudetType;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCurrencyTypeCompany;
        protected System.Web.UI.WebControls.Label lblCurrencyTypeCompany;
        protected LAjitControls.LAjitDropDownList ddlCurrencyTypeCompany;
        protected LAjitControls.LAjitRequiredFieldValidator reqCurrencyTypeCompany;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDefaultBudget;
        protected System.Web.UI.WebControls.Label lblDefaultBudget;
        protected LAjitControls.LAjitCheckBox chkDefaultBudget;
        protected System.Web.UI.HtmlControls.HtmlTableRow trLockedBudget;
        protected System.Web.UI.WebControls.Label lblLockedBudget;
        protected LAjitControls.LAjitCheckBox chkLockedBudget;
        protected System.Web.UI.HtmlControls.HtmlTableRow trImportDate;
        protected System.Web.UI.WebControls.Label lblImportDate;
        protected LAjitControls.LAjitTextBox txtImportDate;
        protected LAjitControls.LAjitRequiredFieldValidator reqImportDate;
        protected System.Web.UI.HtmlControls.HtmlTableRow trImportBy;
        protected System.Web.UI.WebControls.Label lblImportBy;
        protected LAjitControls.LAjitTextBox txtImportBy;
        protected LAjitControls.LAjitRequiredFieldValidator reqImportBy;
        protected System.Web.UI.HtmlControls.HtmlTableRow trYearEndDate;
        protected System.Web.UI.WebControls.Label lblYearEndDate;
        protected LAjitControls.LAjitTextBox txtYearEndDate;
        protected LAjitControls.LAjitRequiredFieldValidator reqYearEndDate;
        protected System.Web.UI.HtmlControls.HtmlTableRow trBPGID;
        protected System.Web.UI.WebControls.Label lblBPGID;
        protected LAjitControls.LAjitTextBox txtBPGID;
        protected LAjitControls.LAjitRequiredFieldValidator reqBPGID;
        protected System.Web.UI.HtmlControls.HtmlTableRow trBPGID2;
        protected System.Web.UI.WebControls.Label lblBPGID2;
        protected LAjitControls.LAjitTextBox txtBPGID2;
        protected LAjitControls.LAjitRequiredFieldValidator reqBPGID2;
        protected System.Web.UI.HtmlControls.HtmlTableRow trBidSoftwareType;
        protected System.Web.UI.WebControls.Label lblBidSoftwareType;
        protected LAjitControls.LAjitDropDownList ddlBidSoftwareType;
        protected LAjitControls.LAjitRequiredFieldValidator reqBidSoftwareType;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
    }
}
