//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Financials {
    
    public partial class JobBudget {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTable tblEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSoxApprovedStatus;
        protected LAjitControls.LAjitImageButton imgbtnIsApproved;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAICPGroup;
        protected System.Web.UI.WebControls.Label lblAICPGroup;
        protected LAjitControls.LAjitTextBox txtAICPGroup;
        protected LAjitControls.LAjitRequiredFieldValidator reqAICPGroup;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCaption;
        protected System.Web.UI.WebControls.Label lblCaption;
        protected LAjitControls.LAjitTextBox txtCaption;
        protected LAjitControls.LAjitRequiredFieldValidator reqCaption;
        protected System.Web.UI.HtmlControls.HtmlTableRow trBidContract;
        protected System.Web.UI.WebControls.Label lblBidContract;
        protected LAjitControls.LAjitTextBox txtBidContract;
        protected LAjitControls.LAjitRequiredFieldValidator reqBidContract;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProdActual;
        protected System.Web.UI.WebControls.Label lblProdActual;
        protected LAjitControls.LAjitTextBox txtProdActual;
        protected LAjitControls.LAjitRequiredFieldValidator reqProdActual;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCommitPO;
        protected System.Web.UI.WebControls.Label lblCommitPO;
        protected LAjitControls.LAjitTextBox txtCommitPO;
        protected LAjitControls.LAjitRequiredFieldValidator reqCommitPO;
        protected System.Web.UI.HtmlControls.HtmlTableRow trBudetType;
        protected System.Web.UI.WebControls.Label lblBudetType;
        protected LAjitControls.LAjitDropDownList ddlBudetType;
        protected LAjitControls.LAjitRequiredFieldValidator reqBudetType;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDescription;
        protected System.Web.UI.WebControls.Label lblDescription;
        protected LAjitControls.LAjitTextBox txtDescription;
        protected LAjitControls.LAjitRequiredFieldValidator reqDescription;
        protected System.Web.UI.WebControls.Label lblCurrencyTypeCompany;
        protected LAjitControls.LAjitDropDownList ddlCurrencyTypeCompany;
        protected LAjitControls.LAjitRequiredFieldValidator reqCurrencyTypeCompany;
        protected System.Web.UI.HtmlControls.HtmlTableRow trYearEndDate;
        protected System.Web.UI.WebControls.Label lblYearEndDate;
        protected LAjitControls.LAjitTextBox txtYearEndDate;
        protected LAjitControls.LAjitRequiredFieldValidator reqYearEndDate;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPaidToDate;
        protected System.Web.UI.WebControls.Label lblPaidToDate;
        protected LAjitControls.LAjitTextBox txtPaidToDate;
        protected LAjitControls.LAjitRequiredFieldValidator reqPaidToDate;
        protected System.Web.UI.HtmlControls.HtmlTableRow trTotalCost;
        protected System.Web.UI.WebControls.Label lblTotalCost;
        protected LAjitControls.LAjitTextBox txtTotalCost;
        protected LAjitControls.LAjitRequiredFieldValidator reqTotalCost;
        protected System.Web.UI.HtmlControls.HtmlTableRow trBudgetVariance;
        protected System.Web.UI.WebControls.Label lblBudgetVariance;
        protected LAjitControls.LAjitTextBox txtBudgetVariance;
        protected LAjitControls.LAjitRequiredFieldValidator reqBudgetVariance;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProdVariance;
        protected System.Web.UI.WebControls.Label lblProdVariance;
        protected LAjitControls.LAjitTextBox txtProdVariance;
        protected LAjitControls.LAjitRequiredFieldValidator reqProdVariance;
        protected LAjitDev.UserControls.ChildGridView CGVUC;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
    }
}
