//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Financials {
    
    public partial class JobType {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlBtnsContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSoxApprovedStatus;
        protected LAjitControls.LAjitImageButton imgbtnIsApproved;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDescription;
        protected System.Web.UI.WebControls.Label lblDescription;
        protected LAjitControls.LAjitTextBox txtDescription;
        protected LAjitControls.LAjitRequiredFieldValidator reqDescription;
        protected LAjitControls.LAjitImage imgTypeOfJob;
        protected System.Web.UI.HtmlControls.HtmlTableRow trTypeOfJob;
        protected System.Web.UI.WebControls.Label lblTypeOfJob;
        protected LAjitControls.LAjitDropDownList ddlTypeOfJob;
        protected LAjitControls.LAjitRequiredFieldValidator reqTypeOfJob;
        protected System.Web.UI.HtmlControls.HtmlTableRow trJobAccountHeading;
        protected System.Web.UI.WebControls.Label lblJobAccountHeading;
        protected LAjitControls.LAjitDropDownList ddlJobAccountHeading;
        protected LAjitControls.LAjitRequiredFieldValidator reqJobAccountHeading;
        protected System.Web.UI.HtmlControls.HtmlTableRow trJobBudgetLayout;
        protected System.Web.UI.WebControls.Label lblJobBudgetLayout;
        protected LAjitControls.LAjitDropDownList ddlJobBudgetLayout;
        protected LAjitControls.LAjitRequiredFieldValidator reqJobBudgetLayout;
        protected System.Web.UI.HtmlControls.HtmlTableRow trJobCOA;
        protected System.Web.UI.WebControls.Label lblJobCOA;
        protected LAjitControls.LAjitDropDownList ddlJobCOA;
        protected LAjitControls.LAjitRequiredFieldValidator reqJobCOA;
        protected System.Web.UI.HtmlControls.HtmlTableRow trJobFormatMask;
        protected System.Web.UI.WebControls.Label lblJobFormatMask;
        protected LAjitControls.LAjitDropDownList ddlJobFormatMask;
        protected LAjitControls.LAjitRequiredFieldValidator reqJobFormatMask;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.WebControls.HiddenField hdnFldTypeOfJob;
    }
}
