//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev {
    
    public partial class JournalsHyb {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlBtnsContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected LAjitDev.ParentChildGV PCGVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trTotal;
        protected System.Web.UI.WebControls.Label lblTotal;
        protected LAjitControls.LAjitTextBox txtTotal;
        protected LAjitControls.LAjitRequiredFieldValidator reqTotal;
        protected LAjitDev.UserControls.ChildGridView CGVUC;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.WebControls.HiddenField hdnRowsToDeleteAccountingItem;
        protected System.Web.UI.WebControls.HiddenField hdnRowCountAccountingItem;
        protected System.Web.UI.WebControls.HiddenField hdnAddedRowsAccountingItem;
    }
}
