//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Financials {
    
    public partial class Pettycashjournal {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSoxApprovedStatus;
        protected LAjitControls.LAjitImageButton imgbtnIsApproved;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSelectPCVendor_JournalDoc;
        protected System.Web.UI.WebControls.Label lblSelectPCVendor_JournalDoc;
        protected LAjitControls.LAjitDropDownList ddlSelectPCVendor_JournalDoc;
        protected LAjitControls.LAjitRequiredFieldValidator reqSelectPCVendor_JournalDoc;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDescription;
        protected System.Web.UI.WebControls.Label lblDescription;
        protected LAjitControls.LAjitTextBox txtDescription;
        protected LAjitControls.LAjitRequiredFieldValidator reqDescription;
        protected System.Web.UI.HtmlControls.HtmlTableRow trEnvelopeReference;
        protected System.Web.UI.WebControls.Label lblEnvelopeReference;
        protected LAjitControls.LAjitTextBox txtEnvelopeReference;
        protected LAjitControls.LAjitRequiredFieldValidator reqEnvelopeReference;
        protected System.Web.UI.HtmlControls.HtmlTableRow trEnvelopeDate;
        protected System.Web.UI.WebControls.Label lblEnvelopeDate;
        protected LAjitControls.LAjitTextBox txtEnvelopeDate;
        protected LAjitControls.LAjitRequiredFieldValidator reqEnvelopeDate;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSelectBatch_JournalDoc;
        protected System.Web.UI.WebControls.Label lblSelectBatch_JournalDoc;
        protected LAjitControls.LAjitDropDownList ddlSelectBatch_JournalDoc;
        protected LAjitControls.LAjitRequiredFieldValidator reqSelectBatch_JournalDoc;
        protected System.Web.UI.HtmlControls.HtmlTableRow trJournalRef;
        protected System.Web.UI.WebControls.Label lblJournalRef;
        protected LAjitControls.LAjitTextBox txtJournalRef;
        protected LAjitControls.LAjitRequiredFieldValidator reqJournalRef;
        protected System.Web.UI.HtmlControls.HtmlTableRow trEnvelopeTotal;
        protected System.Web.UI.WebControls.Label lblEnvelopeTotal;
        protected LAjitControls.LAjitTextBox txtEnvelopeTotal;
        protected LAjitControls.LAjitRequiredFieldValidator reqEnvelopeTotal;
        protected LAjitControls.LAjitRegularExpressionValidator regEnvelopeTotal;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCurrencyTypeCompany;
        protected System.Web.UI.WebControls.Label lblCurrencyTypeCompany;
        protected LAjitControls.LAjitDropDownList ddlCurrencyTypeCompany;
        protected LAjitControls.LAjitRequiredFieldValidator reqCurrencyTypeCompany;
        protected LAjitDev.UserControls.ChildGridView CGVUC;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
    }
}
