//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Financials {
    
    public partial class ProfitVariable {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlBtnsContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSoxApprovedStatus;
        protected LAjitControls.LAjitImageButton imgbtnIsApproved;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSelectProfitVariable;
        protected System.Web.UI.WebControls.Label lblSelectProfitVariable;
        protected LAjitControls.LAjitDropDownList ddlSelectProfitVariable;
        protected LAjitControls.LAjitRequiredFieldValidator reqSelectProfitVariable;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSelectProfitAmt1;
        protected System.Web.UI.WebControls.Label lblSelectProfitAmt1;
        protected LAjitControls.LAjitDropDownList ddlSelectProfitAmt1;
        protected LAjitControls.LAjitRequiredFieldValidator reqSelectProfitAmt1;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSelectProfVarExInc;
        protected System.Web.UI.WebControls.Label lblSelectProfVarExInc;
        protected LAjitControls.LAjitDropDownList ddlSelectProfVarExInc;
        protected LAjitControls.LAjitRequiredFieldValidator reqSelectProfVarExInc;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAutoFillJob;
        protected System.Web.UI.WebControls.Label lblAutoFillJob;
        protected LAjitControls.LAjitTextBox txtAutoFillJob;
        protected LAjitControls.LAjitRequiredFieldValidator reqAutoFillJob;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAutoFillAccount;
        protected System.Web.UI.WebControls.Label lblAutoFillAccount;
        protected LAjitControls.LAjitTextBox txtAutoFillAccount;
        protected LAjitControls.LAjitRequiredFieldValidator reqAutoFillAccount;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAutoFillSubAccount1;
        protected System.Web.UI.WebControls.Label lblAutoFillSubAccount1;
        protected LAjitControls.LAjitTextBox txtAutoFillSubAccount1;
        protected LAjitControls.LAjitRequiredFieldValidator reqAutoFillSubAccount1;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSelectARBillType;
        protected System.Web.UI.WebControls.Label lblSelectARBillType;
        protected LAjitControls.LAjitDropDownList ddlSelectARBillType;
        protected LAjitControls.LAjitRequiredFieldValidator reqSelectARBillType;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
    }
}
