//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Financials {
    
    public partial class ProjectPCAcct {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlBtnsContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTable tblEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPCVendor;
        protected System.Web.UI.WebControls.Label lblPCVendor;
        protected LAjitControls.LAjitDropDownList ddlPCVendor;
        protected LAjitControls.LAjitRequiredFieldValidator reqPCVendor;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPayTo;
        protected System.Web.UI.WebControls.Label lblPayTo;
        protected LAjitControls.LAjitTextBox txtPayTo;
        protected LAjitControls.LAjitRequiredFieldValidator reqPayTo;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPCAccounts;
        protected System.Web.UI.WebControls.Label lblPCAccounts;
        protected LAjitControls.LAjitDropDownList ddlPCAccounts;
        protected LAjitControls.LAjitRequiredFieldValidator reqPCAccounts;
        protected System.Web.UI.HtmlControls.HtmlTableRow trFloatAmount;
        protected System.Web.UI.WebControls.Label lblFloatAmount;
        protected LAjitControls.LAjitTextBox txtFloatAmount;
        protected LAjitControls.LAjitRequiredFieldValidator reqFloatAmount;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCustodianAcct;
        protected System.Web.UI.WebControls.Label lblCustodianAcct;
        protected LAjitControls.LAjitCheckBox chkCustodianAcct;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAdvances;
        protected System.Web.UI.WebControls.Label lblAdvances;
        protected LAjitControls.LAjitTextBox txtAdvances;
        protected LAjitControls.LAjitRequiredFieldValidator reqAdvances;
        protected System.Web.UI.HtmlControls.HtmlTableRow trExpAlloc;
        protected System.Web.UI.WebControls.Label lblExpAlloc;
        protected LAjitControls.LAjitTextBox txtExpAlloc;
        protected LAjitControls.LAjitRequiredFieldValidator reqExpAlloc;
        protected System.Web.UI.HtmlControls.HtmlTableRow trRetDep;
        protected System.Web.UI.WebControls.Label lblRetDep;
        protected LAjitControls.LAjitTextBox txtRetDep;
        protected LAjitControls.LAjitRequiredFieldValidator reqRetDep;
        protected System.Web.UI.HtmlControls.HtmlTableRow trOwed;
        protected System.Web.UI.WebControls.Label lblOwed;
        protected LAjitControls.LAjitTextBox txtOwed;
        protected LAjitControls.LAjitRequiredFieldValidator reqOwed;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
    }
}
