//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Financials {
    
    public partial class Project {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlBtnsContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSoxApprovedStatus;
        protected LAjitControls.LAjitImageButton imgbtnIsApproved;
        protected System.Web.UI.HtmlControls.HtmlTableRow trNumberID;
        protected System.Web.UI.WebControls.Label lblNumberID;
        protected LAjitControls.LAjitTextBox txtNumberID;
        protected LAjitControls.LAjitRequiredFieldValidator reqNumberID;
        protected System.Web.UI.HtmlControls.HtmlTableRow trTitleDef;
        protected System.Web.UI.WebControls.Label lblTitleDef;
        protected LAjitControls.LAjitTextBox txtTitleDef;
        protected LAjitControls.LAjitRequiredFieldValidator reqTitleDef;
        protected LAjitControls.LAjitImage imgTypeOfJob;
        protected System.Web.UI.HtmlControls.HtmlTableRow trTypeOfJob;
        protected System.Web.UI.WebControls.Label lblTypeOfJob;
        protected LAjitControls.LAjitDropDownList ddlTypeOfJob;
        protected LAjitControls.LAjitRequiredFieldValidator reqTypeOfJob;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCenterType;
        protected System.Web.UI.WebControls.Label lblCenterType;
        protected LAjitControls.LAjitDropDownList ddlCenterType;
        protected LAjitControls.LAjitRequiredFieldValidator reqCenterType;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCOAType;
        protected System.Web.UI.WebControls.Label lblCOAType;
        protected LAjitControls.LAjitDropDownList ddlCOAType;
        protected LAjitControls.LAjitRequiredFieldValidator reqCOAType;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSharedCOA;
        protected System.Web.UI.WebControls.Label lblSharedCOA;
        protected LAjitControls.LAjitCheckBox chkbxSharedCOA;
        protected System.Web.UI.HtmlControls.HtmlTableRow trRollupAccount;
        protected System.Web.UI.WebControls.Label lblRollupAccount;
        protected LAjitControls.LAjitDropDownList ddlRollupAccount;
        protected LAjitControls.LAjitRequiredFieldValidator reqRollupAccount;
        protected System.Web.UI.HtmlControls.HtmlTableRow trRollupJob;
        protected System.Web.UI.WebControls.Label lblRollupJob;
        protected LAjitControls.LAjitDropDownList ddlRollupJob;
        protected LAjitControls.LAjitRequiredFieldValidator reqRollupJob;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSelectVATRecovery;
        protected System.Web.UI.WebControls.Label lblSelectVATRecovery;
        protected LAjitControls.LAjitDropDownList ddlSelectVATRecovery;
        protected LAjitControls.LAjitRequiredFieldValidator reqSelectVATRecovery;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCurrencyTypeCompany;
        protected System.Web.UI.WebControls.Label lblCurrencyTypeCompany;
        protected LAjitControls.LAjitDropDownList ddlCurrencyTypeCompany;
        protected LAjitControls.LAjitRequiredFieldValidator reqCurrencyTypeCompany;
        protected System.Web.UI.HtmlControls.HtmlTableRow trImgSrc;
        protected System.Web.UI.WebControls.Label lblImgSrc;
        protected LAjitControls.LAjitTextBox txtImgSrc;
        protected LAjitControls.LAjitRequiredFieldValidator reqImgSrc;
        protected System.Web.UI.HtmlControls.HtmlTableRow trBPGID;
        protected System.Web.UI.WebControls.Label lblBPGID;
        protected LAjitControls.LAjitTextBox txtBPGID;
        protected LAjitControls.LAjitRequiredFieldValidator reqBPGID;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPageInfo;
        protected System.Web.UI.WebControls.Label lblPageInfo;
        protected LAjitControls.LAjitTextBox txtPageInfo;
        protected LAjitControls.LAjitRequiredFieldValidator reqPageInfo;
        protected System.Web.UI.HtmlControls.HtmlTableRow trIsApproved;
        protected System.Web.UI.WebControls.Label lblIsApproved;
        protected LAjitControls.LAjitTextBox txtIsApproved;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSelectSubAccount;
        protected System.Web.UI.WebControls.Label lblSelectSubAccount;
        protected LAjitControls.LAjitListBox lstBxSelectSubAccount;
        protected LAjitControls.LAjitRequiredFieldValidator reqSelectSubAccount;
        protected System.Web.UI.HtmlControls.HtmlTableRow trBidSoftwareType;
        protected System.Web.UI.WebControls.Label lblBidSoftwareType;
        protected LAjitControls.LAjitDropDownList ddlBidSoftwareType;
        protected LAjitControls.LAjitRequiredFieldValidator reqBidSoftwareType;
        protected System.Web.UI.HtmlControls.HtmlTableRow trJobStatus;
        protected System.Web.UI.WebControls.Label lblJobStatus;
        protected LAjitControls.LAjitDropDownList ddlJobStatus;
        protected LAjitControls.LAjitRequiredFieldValidator reqJobStatus;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.WebControls.HiddenField hdnFldTypeOfJob;
    }
}
