//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev {
    
    public partial class PopUp {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm frmMaster;
        protected System.Web.UI.ScriptManager topLeftScriptMngr;
        protected System.Web.UI.WebControls.Panel pnlPopUp;
        protected System.Web.UI.WebControls.ContentPlaceHolder cphPageContents;
        protected System.Web.UI.WebControls.Panel pnlPagePopUp;
        protected System.Web.UI.WebControls.LinkButton lnkBtnCloseIFrame;
        protected System.Web.UI.WebControls.HiddenField test;
        protected System.Web.UI.WebControls.HiddenField hdnResolution;
        protected System.Web.UI.WebControls.HiddenField hdnMasterDummy;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hdnThemeName;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hdnImagesCDNPath;
        protected System.Web.UI.WebControls.ValidationSummary valSummmaryEntryForm;
    }
}
