//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Banking {
    
    public partial class BankControl {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlBtnsContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTable tblEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trEntryBank;
        protected System.Web.UI.WebControls.Label lblEntryBank;
        protected LAjitControls.LAjitDropDownList ddlEntryBank;
        protected LAjitControls.LAjitRequiredFieldValidator reqEntryBank;
        protected System.Web.UI.HtmlControls.HtmlTableRow trEndDate;
        protected System.Web.UI.WebControls.Label lblEndDate;
        protected LAjitControls.LAjitTextBox txtEndDate;
        protected LAjitControls.LAjitRequiredFieldValidator reqEndDate;
        protected System.Web.UI.HtmlControls.HtmlTableRow trOpenBalance;
        protected System.Web.UI.WebControls.Label lblOpenBalance;
        protected LAjitControls.LAjitTextBox txtOpenBalance;
        protected LAjitControls.LAjitRequiredFieldValidator reqOpenBalance;
        protected System.Web.UI.HtmlControls.HtmlTableRow trEndBal;
        protected System.Web.UI.WebControls.Label lblEndBal;
        protected LAjitControls.LAjitTextBox txtEndBal;
        protected LAjitControls.LAjitRequiredFieldValidator reqEndBal;
        protected System.Web.UI.HtmlControls.HtmlTableRow trGLEndBal;
        protected System.Web.UI.WebControls.Label lblGLEndBal;
        protected LAjitControls.LAjitTextBox txtGLEndBal;
        protected LAjitControls.LAjitRequiredFieldValidator reqGLEndBal;
        protected System.Web.UI.HtmlControls.HtmlTableRow trClearedChecks;
        protected System.Web.UI.WebControls.Label lblClearedChecks;
        protected LAjitControls.LAjitTextBox txtClearedChecks;
        protected LAjitControls.LAjitRequiredFieldValidator reqClearedChecks;
        protected System.Web.UI.HtmlControls.HtmlTableRow trClearedDeposits;
        protected System.Web.UI.WebControls.Label lblClearedDeposits;
        protected LAjitControls.LAjitTextBox txtClearedDeposits;
        protected LAjitControls.LAjitRequiredFieldValidator reqClearedDeposits;
        protected System.Web.UI.HtmlControls.HtmlTableRow trClearedAdjs;
        protected System.Web.UI.WebControls.Label lblClearedAdjs;
        protected LAjitControls.LAjitTextBox txtClearedAdjs;
        protected LAjitControls.LAjitRequiredFieldValidator reqClearedAdjs;
        protected System.Web.UI.HtmlControls.HtmlTableRow trBankCharges;
        protected System.Web.UI.WebControls.Label lblBankCharges;
        protected LAjitControls.LAjitTextBox txtBankCharges;
        protected LAjitControls.LAjitRequiredFieldValidator reqBankCharges;
        protected System.Web.UI.HtmlControls.HtmlTableRow trLedgerBalance;
        protected System.Web.UI.WebControls.Label lblLedgerBalance;
        protected LAjitControls.LAjitTextBox txtLedgerBalance;
        protected LAjitControls.LAjitRequiredFieldValidator reqLedgerBalance;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
    }
}
