//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace LAjitDev.Fedex_Track_Services {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TrackServiceSoapBinding", Namespace="http://fedex.com/ws/track/v2")]
    public partial class TrackService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback trackOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTrackNotificationOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSignatureProofOfDeliveryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TrackService() {
            this.Url = global::LAjitDev.Properties.Settings.Default.LAjitDev_Fedex_Track_Services;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event trackCompletedEventHandler trackCompleted;
        
        /// <remarks/>
        public event getTrackNotificationCompletedEventHandler getTrackNotificationCompleted;
        
        /// <remarks/>
        public event getSignatureProofOfDeliveryCompletedEventHandler getSignatureProofOfDeliveryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("track", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("TrackReply", Namespace="http://fedex.com/ws/track/v2")]
        public TrackReply track([System.Xml.Serialization.XmlElementAttribute(Namespace="http://fedex.com/ws/track/v2")] TrackRequest TrackRequest) {
            object[] results = this.Invoke("track", new object[] {
                        TrackRequest});
            return ((TrackReply)(results[0]));
        }
        
        /// <remarks/>
        public void trackAsync(TrackRequest TrackRequest) {
            this.trackAsync(TrackRequest, null);
        }
        
        /// <remarks/>
        public void trackAsync(TrackRequest TrackRequest, object userState) {
            if ((this.trackOperationCompleted == null)) {
                this.trackOperationCompleted = new System.Threading.SendOrPostCallback(this.OntrackOperationCompleted);
            }
            this.InvokeAsync("track", new object[] {
                        TrackRequest}, this.trackOperationCompleted, userState);
        }
        
        private void OntrackOperationCompleted(object arg) {
            if ((this.trackCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.trackCompleted(this, new trackCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getTrackNotification", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("TrackNotificationReply", Namespace="http://fedex.com/ws/track/v2")]
        public TrackNotificationReply getTrackNotification([System.Xml.Serialization.XmlElementAttribute(Namespace="http://fedex.com/ws/track/v2")] TrackNotificationRequest TrackNotificationRequest) {
            object[] results = this.Invoke("getTrackNotification", new object[] {
                        TrackNotificationRequest});
            return ((TrackNotificationReply)(results[0]));
        }
        
        /// <remarks/>
        public void getTrackNotificationAsync(TrackNotificationRequest TrackNotificationRequest) {
            this.getTrackNotificationAsync(TrackNotificationRequest, null);
        }
        
        /// <remarks/>
        public void getTrackNotificationAsync(TrackNotificationRequest TrackNotificationRequest, object userState) {
            if ((this.getTrackNotificationOperationCompleted == null)) {
                this.getTrackNotificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTrackNotificationOperationCompleted);
            }
            this.InvokeAsync("getTrackNotification", new object[] {
                        TrackNotificationRequest}, this.getTrackNotificationOperationCompleted, userState);
        }
        
        private void OngetTrackNotificationOperationCompleted(object arg) {
            if ((this.getTrackNotificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTrackNotificationCompleted(this, new getTrackNotificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getSignatureProofOfDelivery", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SignatureProofOfDeliveryReply", Namespace="http://fedex.com/ws/track/v2")]
        public SignatureProofOfDeliveryReply getSignatureProofOfDelivery([System.Xml.Serialization.XmlElementAttribute(Namespace="http://fedex.com/ws/track/v2")] SignatureProofOfDeliveryRequest SignatureProofOfDeliveryRequest) {
            object[] results = this.Invoke("getSignatureProofOfDelivery", new object[] {
                        SignatureProofOfDeliveryRequest});
            return ((SignatureProofOfDeliveryReply)(results[0]));
        }
        
        /// <remarks/>
        public void getSignatureProofOfDeliveryAsync(SignatureProofOfDeliveryRequest SignatureProofOfDeliveryRequest) {
            this.getSignatureProofOfDeliveryAsync(SignatureProofOfDeliveryRequest, null);
        }
        
        /// <remarks/>
        public void getSignatureProofOfDeliveryAsync(SignatureProofOfDeliveryRequest SignatureProofOfDeliveryRequest, object userState) {
            if ((this.getSignatureProofOfDeliveryOperationCompleted == null)) {
                this.getSignatureProofOfDeliveryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSignatureProofOfDeliveryOperationCompleted);
            }
            this.InvokeAsync("getSignatureProofOfDelivery", new object[] {
                        SignatureProofOfDeliveryRequest}, this.getSignatureProofOfDeliveryOperationCompleted, userState);
        }
        
        private void OngetSignatureProofOfDeliveryOperationCompleted(object arg) {
            if ((this.getSignatureProofOfDeliveryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSignatureProofOfDeliveryCompleted(this, new getSignatureProofOfDeliveryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class TrackRequest {
        
        private WebAuthenticationDetail webAuthenticationDetailField;
        
        private ClientDetail clientDetailField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private TrackPackageIdentifier packageIdentifierField;
        
        private string trackingNumberUniqueIdentifierField;
        
        private System.DateTime shipDateRangeBeginField;
        
        private bool shipDateRangeBeginFieldSpecified;
        
        private System.DateTime shipDateRangeEndField;
        
        private bool shipDateRangeEndFieldSpecified;
        
        private string shipmentAccountNumberField;
        
        private Address destinationField;
        
        private bool includeDetailedScansField;
        
        private bool includeDetailedScansFieldSpecified;
        
        private string pagingTokenField;
        
        /// <remarks/>
        public WebAuthenticationDetail WebAuthenticationDetail {
            get {
                return this.webAuthenticationDetailField;
            }
            set {
                this.webAuthenticationDetailField = value;
            }
        }
        
        /// <remarks/>
        public ClientDetail ClientDetail {
            get {
                return this.clientDetailField;
            }
            set {
                this.clientDetailField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDetail TransactionDetail {
            get {
                return this.transactionDetailField;
            }
            set {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        public VersionId Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public TrackPackageIdentifier PackageIdentifier {
            get {
                return this.packageIdentifierField;
            }
            set {
                this.packageIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingNumberUniqueIdentifier {
            get {
                return this.trackingNumberUniqueIdentifierField;
            }
            set {
                this.trackingNumberUniqueIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ShipDateRangeBegin {
            get {
                return this.shipDateRangeBeginField;
            }
            set {
                this.shipDateRangeBeginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipDateRangeBeginSpecified {
            get {
                return this.shipDateRangeBeginFieldSpecified;
            }
            set {
                this.shipDateRangeBeginFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ShipDateRangeEnd {
            get {
                return this.shipDateRangeEndField;
            }
            set {
                this.shipDateRangeEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipDateRangeEndSpecified {
            get {
                return this.shipDateRangeEndFieldSpecified;
            }
            set {
                this.shipDateRangeEndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ShipmentAccountNumber {
            get {
                return this.shipmentAccountNumberField;
            }
            set {
                this.shipmentAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public Address Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public bool IncludeDetailedScans {
            get {
                return this.includeDetailedScansField;
            }
            set {
                this.includeDetailedScansField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncludeDetailedScansSpecified {
            get {
                return this.includeDetailedScansFieldSpecified;
            }
            set {
                this.includeDetailedScansFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string PagingToken {
            get {
                return this.pagingTokenField;
            }
            set {
                this.pagingTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class WebAuthenticationDetail {
        
        private WebAuthenticationCredential userCredentialField;
        
        /// <remarks/>
        public WebAuthenticationCredential UserCredential {
            get {
                return this.userCredentialField;
            }
            set {
                this.userCredentialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class WebAuthenticationCredential {
        
        private string keyField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class SignatureProofOfDeliveryReply {
        
        private NotificationSeverityType highestSeverityField;
        
        private Notification[] notificationsField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private byte[] letterField;
        
        private string faxConfirmationNumberField;
        
        /// <remarks/>
        public NotificationSeverityType HighestSeverity {
            get {
                return this.highestSeverityField;
            }
            set {
                this.highestSeverityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Notifications")]
        public Notification[] Notifications {
            get {
                return this.notificationsField;
            }
            set {
                this.notificationsField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDetail TransactionDetail {
            get {
                return this.transactionDetailField;
            }
            set {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        public VersionId Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Letter {
            get {
                return this.letterField;
            }
            set {
                this.letterField = value;
            }
        }
        
        /// <remarks/>
        public string FaxConfirmationNumber {
            get {
                return this.faxConfirmationNumberField;
            }
            set {
                this.faxConfirmationNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public enum NotificationSeverityType {
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        FAILURE,
        
        /// <remarks/>
        NOTE,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        WARNING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class Notification {
        
        private NotificationSeverityType severityField;
        
        private string sourceField;
        
        private string codeField;
        
        private string messageField;
        
        private string localizedMessageField;
        
        private NotificationParameter[] messageParametersField;
        
        /// <remarks/>
        public NotificationSeverityType Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string LocalizedMessage {
            get {
                return this.localizedMessageField;
            }
            set {
                this.localizedMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MessageParameters")]
        public NotificationParameter[] MessageParameters {
            get {
                return this.messageParametersField;
            }
            set {
                this.messageParametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class NotificationParameter {
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class TransactionDetail {
        
        private string customerTransactionIdField;
        
        private Localization localizationField;
        
        /// <remarks/>
        public string CustomerTransactionId {
            get {
                return this.customerTransactionIdField;
            }
            set {
                this.customerTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        public Localization Localization {
            get {
                return this.localizationField;
            }
            set {
                this.localizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class Localization {
        
        private string languageCodeField;
        
        private string localeCodeField;
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LocaleCode {
            get {
                return this.localeCodeField;
            }
            set {
                this.localeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class VersionId {
        
        private string serviceIdField;
        
        private int majorField;
        
        private int intermediateField;
        
        private int minorField;
        
        public VersionId() {
            this.serviceIdField = "trck";
            this.majorField = 2;
            this.intermediateField = 0;
            this.minorField = 0;
        }
        
        /// <remarks/>
        public string ServiceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        public int Major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
            }
        }
        
        /// <remarks/>
        public int Intermediate {
            get {
                return this.intermediateField;
            }
            set {
                this.intermediateField = value;
            }
        }
        
        /// <remarks/>
        public int Minor {
            get {
                return this.minorField;
            }
            set {
                this.minorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class SignatureProofOfDeliveryFaxDetail {
        
        private Contact senderField;
        
        private Contact faxRecipientField;
        
        private ContactAndAddress mailRecipientField;
        
        /// <remarks/>
        public Contact Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        public Contact FaxRecipient {
            get {
                return this.faxRecipientField;
            }
            set {
                this.faxRecipientField = value;
            }
        }
        
        /// <remarks/>
        public ContactAndAddress MailRecipient {
            get {
                return this.mailRecipientField;
            }
            set {
                this.mailRecipientField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class Contact {
        
        private string personNameField;
        
        private string titleField;
        
        private string companyNameField;
        
        private string departmentField;
        
        private string phoneNumberField;
        
        private string phoneExtensionField;
        
        private string pagerNumberField;
        
        private string faxNumberField;
        
        private string eMailAddressField;
        
        /// <remarks/>
        public string PersonName {
            get {
                return this.personNameField;
            }
            set {
                this.personNameField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneExtension {
            get {
                return this.phoneExtensionField;
            }
            set {
                this.phoneExtensionField = value;
            }
        }
        
        /// <remarks/>
        public string PagerNumber {
            get {
                return this.pagerNumberField;
            }
            set {
                this.pagerNumberField = value;
            }
        }
        
        /// <remarks/>
        public string FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EMailAddress {
            get {
                return this.eMailAddressField;
            }
            set {
                this.eMailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class ContactAndAddress {
        
        private Contact contactField;
        
        private Address addressField;
        
        /// <remarks/>
        public Contact Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class Address {
        
        private string[] streetLinesField;
        
        private string cityField;
        
        private string stateOrProvinceCodeField;
        
        private string postalCodeField;
        
        private string urbanizationCodeField;
        
        private string countryCodeField;
        
        private bool residentialField;
        
        private bool residentialFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StreetLines")]
        public string[] StreetLines {
            get {
                return this.streetLinesField;
            }
            set {
                this.streetLinesField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateOrProvinceCode {
            get {
                return this.stateOrProvinceCodeField;
            }
            set {
                this.stateOrProvinceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UrbanizationCode {
            get {
                return this.urbanizationCodeField;
            }
            set {
                this.urbanizationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool Residential {
            get {
                return this.residentialField;
            }
            set {
                this.residentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResidentialSpecified {
            get {
                return this.residentialFieldSpecified;
            }
            set {
                this.residentialFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class SignatureProofOfDeliveryRequest {
        
        private WebAuthenticationDetail webAuthenticationDetailField;
        
        private ClientDetail clientDetailField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private SignatureProofOfDeliveryRequestType typeField;
        
        private System.DateTime shipDateField;
        
        private bool shipDateFieldSpecified;
        
        private string shipmentAcountNumberField;
        
        private string trackingNumberField;
        
        private ContactAndAddress consigneeField;
        
        private string additionalInformationField;
        
        private SignatureProofOfDeliveryFaxDetail faxDetailField;
        
        private SignatureProofOfDeliveryImageType letterFormatField;
        
        private bool letterFormatFieldSpecified;
        
        /// <remarks/>
        public WebAuthenticationDetail WebAuthenticationDetail {
            get {
                return this.webAuthenticationDetailField;
            }
            set {
                this.webAuthenticationDetailField = value;
            }
        }
        
        /// <remarks/>
        public ClientDetail ClientDetail {
            get {
                return this.clientDetailField;
            }
            set {
                this.clientDetailField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDetail TransactionDetail {
            get {
                return this.transactionDetailField;
            }
            set {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        public VersionId Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public SignatureProofOfDeliveryRequestType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ShipDate {
            get {
                return this.shipDateField;
            }
            set {
                this.shipDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipDateSpecified {
            get {
                return this.shipDateFieldSpecified;
            }
            set {
                this.shipDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ShipmentAcountNumber {
            get {
                return this.shipmentAcountNumberField;
            }
            set {
                this.shipmentAcountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
            }
        }
        
        /// <remarks/>
        public ContactAndAddress Consignee {
            get {
                return this.consigneeField;
            }
            set {
                this.consigneeField = value;
            }
        }
        
        /// <remarks/>
        public string AdditionalInformation {
            get {
                return this.additionalInformationField;
            }
            set {
                this.additionalInformationField = value;
            }
        }
        
        /// <remarks/>
        public SignatureProofOfDeliveryFaxDetail FaxDetail {
            get {
                return this.faxDetailField;
            }
            set {
                this.faxDetailField = value;
            }
        }
        
        /// <remarks/>
        public SignatureProofOfDeliveryImageType LetterFormat {
            get {
                return this.letterFormatField;
            }
            set {
                this.letterFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LetterFormatSpecified {
            get {
                return this.letterFormatFieldSpecified;
            }
            set {
                this.letterFormatFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class ClientDetail {
        
        private string accountNumberField;
        
        private string meterNumberField;
        
        private Localization localizationField;
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MeterNumber {
            get {
                return this.meterNumberField;
            }
            set {
                this.meterNumberField = value;
            }
        }
        
        /// <remarks/>
        public Localization Localization {
            get {
                return this.localizationField;
            }
            set {
                this.localizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public enum SignatureProofOfDeliveryRequestType {
        
        /// <remarks/>
        FAX,
        
        /// <remarks/>
        LETTER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public enum SignatureProofOfDeliveryImageType {
        
        /// <remarks/>
        PDF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class TrackNotificationRecipientDetail {
        
        private bool notifyOnDeliveryField;
        
        private bool notifyOnDeliveryFieldSpecified;
        
        private bool notifyOnExceptionField;
        
        private bool notifyOnExceptionFieldSpecified;
        
        /// <remarks/>
        public bool NotifyOnDelivery {
            get {
                return this.notifyOnDeliveryField;
            }
            set {
                this.notifyOnDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotifyOnDeliverySpecified {
            get {
                return this.notifyOnDeliveryFieldSpecified;
            }
            set {
                this.notifyOnDeliveryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool NotifyOnException {
            get {
                return this.notifyOnExceptionField;
            }
            set {
                this.notifyOnExceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotifyOnExceptionSpecified {
            get {
                return this.notifyOnExceptionFieldSpecified;
            }
            set {
                this.notifyOnExceptionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class TrackNotificationPackage {
        
        private string trackingNumberField;
        
        private string trackingNumberUniqueIdentifiersField;
        
        private CarrierCodeType carrierCodeField;
        
        private bool carrierCodeFieldSpecified;
        
        private System.DateTime shipDateField;
        
        private bool shipDateFieldSpecified;
        
        private Address destinationField;
        
        private TrackNotificationRecipientDetail[] recipientDetailsField;
        
        /// <remarks/>
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingNumberUniqueIdentifiers {
            get {
                return this.trackingNumberUniqueIdentifiersField;
            }
            set {
                this.trackingNumberUniqueIdentifiersField = value;
            }
        }
        
        /// <remarks/>
        public CarrierCodeType CarrierCode {
            get {
                return this.carrierCodeField;
            }
            set {
                this.carrierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CarrierCodeSpecified {
            get {
                return this.carrierCodeFieldSpecified;
            }
            set {
                this.carrierCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ShipDate {
            get {
                return this.shipDateField;
            }
            set {
                this.shipDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipDateSpecified {
            get {
                return this.shipDateFieldSpecified;
            }
            set {
                this.shipDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Address Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecipientDetails")]
        public TrackNotificationRecipientDetail[] RecipientDetails {
            get {
                return this.recipientDetailsField;
            }
            set {
                this.recipientDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public enum CarrierCodeType {
        
        /// <remarks/>
        FDXC,
        
        /// <remarks/>
        FDXE,
        
        /// <remarks/>
        FDXG,
        
        /// <remarks/>
        FXCC,
        
        /// <remarks/>
        FXFR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class TrackNotificationReply {
        
        private NotificationSeverityType highestSeverityField;
        
        private Notification[] notificationsField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private bool duplicateWaybillField;
        
        private bool duplicateWaybillFieldSpecified;
        
        private bool moreDataAvailableField;
        
        private bool moreDataAvailableFieldSpecified;
        
        private string pagingTokenField;
        
        private TrackNotificationPackage[] packagesField;
        
        /// <remarks/>
        public NotificationSeverityType HighestSeverity {
            get {
                return this.highestSeverityField;
            }
            set {
                this.highestSeverityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Notifications")]
        public Notification[] Notifications {
            get {
                return this.notificationsField;
            }
            set {
                this.notificationsField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDetail TransactionDetail {
            get {
                return this.transactionDetailField;
            }
            set {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        public VersionId Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public bool DuplicateWaybill {
            get {
                return this.duplicateWaybillField;
            }
            set {
                this.duplicateWaybillField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DuplicateWaybillSpecified {
            get {
                return this.duplicateWaybillFieldSpecified;
            }
            set {
                this.duplicateWaybillFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool MoreDataAvailable {
            get {
                return this.moreDataAvailableField;
            }
            set {
                this.moreDataAvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MoreDataAvailableSpecified {
            get {
                return this.moreDataAvailableFieldSpecified;
            }
            set {
                this.moreDataAvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string PagingToken {
            get {
                return this.pagingTokenField;
            }
            set {
                this.pagingTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Packages")]
        public TrackNotificationPackage[] Packages {
            get {
                return this.packagesField;
            }
            set {
                this.packagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class EMailNotificationRecipient {
        
        private EMailNotificationRecipientType eMailNotificationRecipientTypeField;
        
        private bool eMailNotificationRecipientTypeFieldSpecified;
        
        private string eMailAddressField;
        
        private bool notifyOnShipmentField;
        
        private bool notifyOnShipmentFieldSpecified;
        
        private bool notifyOnExceptionField;
        
        private bool notifyOnExceptionFieldSpecified;
        
        private bool notifyOnDeliveryField;
        
        private bool notifyOnDeliveryFieldSpecified;
        
        private EMailNotificationFormatType formatField;
        
        private Localization localizationField;
        
        /// <remarks/>
        public EMailNotificationRecipientType EMailNotificationRecipientType {
            get {
                return this.eMailNotificationRecipientTypeField;
            }
            set {
                this.eMailNotificationRecipientTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EMailNotificationRecipientTypeSpecified {
            get {
                return this.eMailNotificationRecipientTypeFieldSpecified;
            }
            set {
                this.eMailNotificationRecipientTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EMailAddress {
            get {
                return this.eMailAddressField;
            }
            set {
                this.eMailAddressField = value;
            }
        }
        
        /// <remarks/>
        public bool NotifyOnShipment {
            get {
                return this.notifyOnShipmentField;
            }
            set {
                this.notifyOnShipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotifyOnShipmentSpecified {
            get {
                return this.notifyOnShipmentFieldSpecified;
            }
            set {
                this.notifyOnShipmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool NotifyOnException {
            get {
                return this.notifyOnExceptionField;
            }
            set {
                this.notifyOnExceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotifyOnExceptionSpecified {
            get {
                return this.notifyOnExceptionFieldSpecified;
            }
            set {
                this.notifyOnExceptionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool NotifyOnDelivery {
            get {
                return this.notifyOnDeliveryField;
            }
            set {
                this.notifyOnDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotifyOnDeliverySpecified {
            get {
                return this.notifyOnDeliveryFieldSpecified;
            }
            set {
                this.notifyOnDeliveryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public EMailNotificationFormatType Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        public Localization Localization {
            get {
                return this.localizationField;
            }
            set {
                this.localizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public enum EMailNotificationRecipientType {
        
        /// <remarks/>
        BROKER,
        
        /// <remarks/>
        OTHER,
        
        /// <remarks/>
        RECIPIENT,
        
        /// <remarks/>
        SHIPPER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public enum EMailNotificationFormatType {
        
        /// <remarks/>
        HTML,
        
        /// <remarks/>
        TEXT,
        
        /// <remarks/>
        WIRELESS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class EMailNotificationDetail {
        
        private string personalMessageField;
        
        private EMailNotificationRecipient[] recipientsField;
        
        /// <remarks/>
        public string PersonalMessage {
            get {
                return this.personalMessageField;
            }
            set {
                this.personalMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Recipients")]
        public EMailNotificationRecipient[] Recipients {
            get {
                return this.recipientsField;
            }
            set {
                this.recipientsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class TrackNotificationRequest {
        
        private WebAuthenticationDetail webAuthenticationDetailField;
        
        private ClientDetail clientDetailField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private string trackingNumberField;
        
        private bool multiPieceField;
        
        private bool multiPieceFieldSpecified;
        
        private string pagingTokenField;
        
        private string trackingNumberUniqueIdField;
        
        private System.DateTime shipDateRangeBeginField;
        
        private bool shipDateRangeBeginFieldSpecified;
        
        private System.DateTime shipDateRangeEndField;
        
        private bool shipDateRangeEndFieldSpecified;
        
        private string senderEMailAddressField;
        
        private string senderContactNameField;
        
        private EMailNotificationDetail notificationDetailField;
        
        /// <remarks/>
        public WebAuthenticationDetail WebAuthenticationDetail {
            get {
                return this.webAuthenticationDetailField;
            }
            set {
                this.webAuthenticationDetailField = value;
            }
        }
        
        /// <remarks/>
        public ClientDetail ClientDetail {
            get {
                return this.clientDetailField;
            }
            set {
                this.clientDetailField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDetail TransactionDetail {
            get {
                return this.transactionDetailField;
            }
            set {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        public VersionId Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool MultiPiece {
            get {
                return this.multiPieceField;
            }
            set {
                this.multiPieceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MultiPieceSpecified {
            get {
                return this.multiPieceFieldSpecified;
            }
            set {
                this.multiPieceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string PagingToken {
            get {
                return this.pagingTokenField;
            }
            set {
                this.pagingTokenField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingNumberUniqueId {
            get {
                return this.trackingNumberUniqueIdField;
            }
            set {
                this.trackingNumberUniqueIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ShipDateRangeBegin {
            get {
                return this.shipDateRangeBeginField;
            }
            set {
                this.shipDateRangeBeginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipDateRangeBeginSpecified {
            get {
                return this.shipDateRangeBeginFieldSpecified;
            }
            set {
                this.shipDateRangeBeginFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ShipDateRangeEnd {
            get {
                return this.shipDateRangeEndField;
            }
            set {
                this.shipDateRangeEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipDateRangeEndSpecified {
            get {
                return this.shipDateRangeEndFieldSpecified;
            }
            set {
                this.shipDateRangeEndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SenderEMailAddress {
            get {
                return this.senderEMailAddressField;
            }
            set {
                this.senderEMailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string SenderContactName {
            get {
                return this.senderContactNameField;
            }
            set {
                this.senderContactNameField = value;
            }
        }
        
        /// <remarks/>
        public EMailNotificationDetail NotificationDetail {
            get {
                return this.notificationDetailField;
            }
            set {
                this.notificationDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class TrackEvent {
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private string eventTypeField;
        
        private string eventDescriptionField;
        
        private string statusExceptionCodeField;
        
        private string statusExceptionDescriptionField;
        
        private Address addressField;
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
            }
        }
        
        /// <remarks/>
        public string EventDescription {
            get {
                return this.eventDescriptionField;
            }
            set {
                this.eventDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string StatusExceptionCode {
            get {
                return this.statusExceptionCodeField;
            }
            set {
                this.statusExceptionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusExceptionDescription {
            get {
                return this.statusExceptionDescriptionField;
            }
            set {
                this.statusExceptionDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class TrackSplitShipmentPart {
        
        private int pieceCountField;
        
        private bool pieceCountFieldSpecified;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        /// <remarks/>
        public int PieceCount {
            get {
                return this.pieceCountField;
            }
            set {
                this.pieceCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PieceCountSpecified {
            get {
                return this.pieceCountFieldSpecified;
            }
            set {
                this.pieceCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class Distance {
        
        private decimal valueField;
        
        private bool valueFieldSpecified;
        
        private DistanceUnits unitsField;
        
        private bool unitsFieldSpecified;
        
        /// <remarks/>
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public DistanceUnits Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitsSpecified {
            get {
                return this.unitsFieldSpecified;
            }
            set {
                this.unitsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public enum DistanceUnits {
        
        /// <remarks/>
        KM,
        
        /// <remarks/>
        MI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class Weight {
        
        private WeightUnits unitsField;
        
        private bool unitsFieldSpecified;
        
        private decimal valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        public WeightUnits Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitsSpecified {
            get {
                return this.unitsFieldSpecified;
            }
            set {
                this.unitsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public enum WeightUnits {
        
        /// <remarks/>
        KG,
        
        /// <remarks/>
        LB,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class TrackReconciliation {
        
        private string statusField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class TrackDetail {
        
        private Notification notificationField;
        
        private string trackingNumberField;
        
        private string trackingNumberUniqueIdentifierField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private TrackReconciliation reconciliationField;
        
        private string serviceCommitMessageField;
        
        private CarrierCodeType carrierCodeField;
        
        private bool carrierCodeFieldSpecified;
        
        private TrackPackageIdentifier[] otherIdentifiersField;
        
        private string serviceInfoField;
        
        private Weight packageWeightField;
        
        private Weight shipmentWeightField;
        
        private string packagingField;
        
        private int packageSequenceNumberField;
        
        private bool packageSequenceNumberFieldSpecified;
        
        private int packageCountField;
        
        private bool packageCountFieldSpecified;
        
        private Address shipperAddressField;
        
        private Address originLocationAddressField;
        
        private System.DateTime estimatedPickupTimestampField;
        
        private bool estimatedPickupTimestampFieldSpecified;
        
        private System.DateTime shipTimestampField;
        
        private bool shipTimestampFieldSpecified;
        
        private Distance totalTransitDistanceField;
        
        private Distance distanceToDestinationField;
        
        private Address destinationAddressField;
        
        private Address destinationLocationAddressField;
        
        private System.DateTime estimatedDeliveryTimestampField;
        
        private bool estimatedDeliveryTimestampFieldSpecified;
        
        private System.DateTime actualDeliveryTimestampField;
        
        private bool actualDeliveryTimestampFieldSpecified;
        
        private string deliveryLocationCodeField;
        
        private string deliveryLocationDescriptionField;
        
        private string deliverySignatureNameField;
        
        private bool signatureProofOfDeliveryAvailableField;
        
        private bool signatureProofOfDeliveryAvailableFieldSpecified;
        
        private bool proofOfDeliveryNotificationsAvailableField;
        
        private bool proofOfDeliveryNotificationsAvailableFieldSpecified;
        
        private bool exceptionNotificationsAvailableField;
        
        private bool exceptionNotificationsAvailableFieldSpecified;
        
        private TrackSplitShipmentPart[] splitShipmentPartsField;
        
        private TrackEvent[] eventsField;
        
        /// <remarks/>
        public Notification Notification {
            get {
                return this.notificationField;
            }
            set {
                this.notificationField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingNumberUniqueIdentifier {
            get {
                return this.trackingNumberUniqueIdentifierField;
            }
            set {
                this.trackingNumberUniqueIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public TrackReconciliation Reconciliation {
            get {
                return this.reconciliationField;
            }
            set {
                this.reconciliationField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceCommitMessage {
            get {
                return this.serviceCommitMessageField;
            }
            set {
                this.serviceCommitMessageField = value;
            }
        }
        
        /// <remarks/>
        public CarrierCodeType CarrierCode {
            get {
                return this.carrierCodeField;
            }
            set {
                this.carrierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CarrierCodeSpecified {
            get {
                return this.carrierCodeFieldSpecified;
            }
            set {
                this.carrierCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OtherIdentifiers")]
        public TrackPackageIdentifier[] OtherIdentifiers {
            get {
                return this.otherIdentifiersField;
            }
            set {
                this.otherIdentifiersField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceInfo {
            get {
                return this.serviceInfoField;
            }
            set {
                this.serviceInfoField = value;
            }
        }
        
        /// <remarks/>
        public Weight PackageWeight {
            get {
                return this.packageWeightField;
            }
            set {
                this.packageWeightField = value;
            }
        }
        
        /// <remarks/>
        public Weight ShipmentWeight {
            get {
                return this.shipmentWeightField;
            }
            set {
                this.shipmentWeightField = value;
            }
        }
        
        /// <remarks/>
        public string Packaging {
            get {
                return this.packagingField;
            }
            set {
                this.packagingField = value;
            }
        }
        
        /// <remarks/>
        public int PackageSequenceNumber {
            get {
                return this.packageSequenceNumberField;
            }
            set {
                this.packageSequenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackageSequenceNumberSpecified {
            get {
                return this.packageSequenceNumberFieldSpecified;
            }
            set {
                this.packageSequenceNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int PackageCount {
            get {
                return this.packageCountField;
            }
            set {
                this.packageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackageCountSpecified {
            get {
                return this.packageCountFieldSpecified;
            }
            set {
                this.packageCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Address ShipperAddress {
            get {
                return this.shipperAddressField;
            }
            set {
                this.shipperAddressField = value;
            }
        }
        
        /// <remarks/>
        public Address OriginLocationAddress {
            get {
                return this.originLocationAddressField;
            }
            set {
                this.originLocationAddressField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EstimatedPickupTimestamp {
            get {
                return this.estimatedPickupTimestampField;
            }
            set {
                this.estimatedPickupTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstimatedPickupTimestampSpecified {
            get {
                return this.estimatedPickupTimestampFieldSpecified;
            }
            set {
                this.estimatedPickupTimestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ShipTimestamp {
            get {
                return this.shipTimestampField;
            }
            set {
                this.shipTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipTimestampSpecified {
            get {
                return this.shipTimestampFieldSpecified;
            }
            set {
                this.shipTimestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Distance TotalTransitDistance {
            get {
                return this.totalTransitDistanceField;
            }
            set {
                this.totalTransitDistanceField = value;
            }
        }
        
        /// <remarks/>
        public Distance DistanceToDestination {
            get {
                return this.distanceToDestinationField;
            }
            set {
                this.distanceToDestinationField = value;
            }
        }
        
        /// <remarks/>
        public Address DestinationAddress {
            get {
                return this.destinationAddressField;
            }
            set {
                this.destinationAddressField = value;
            }
        }
        
        /// <remarks/>
        public Address DestinationLocationAddress {
            get {
                return this.destinationLocationAddressField;
            }
            set {
                this.destinationLocationAddressField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EstimatedDeliveryTimestamp {
            get {
                return this.estimatedDeliveryTimestampField;
            }
            set {
                this.estimatedDeliveryTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstimatedDeliveryTimestampSpecified {
            get {
                return this.estimatedDeliveryTimestampFieldSpecified;
            }
            set {
                this.estimatedDeliveryTimestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ActualDeliveryTimestamp {
            get {
                return this.actualDeliveryTimestampField;
            }
            set {
                this.actualDeliveryTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActualDeliveryTimestampSpecified {
            get {
                return this.actualDeliveryTimestampFieldSpecified;
            }
            set {
                this.actualDeliveryTimestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryLocationCode {
            get {
                return this.deliveryLocationCodeField;
            }
            set {
                this.deliveryLocationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryLocationDescription {
            get {
                return this.deliveryLocationDescriptionField;
            }
            set {
                this.deliveryLocationDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string DeliverySignatureName {
            get {
                return this.deliverySignatureNameField;
            }
            set {
                this.deliverySignatureNameField = value;
            }
        }
        
        /// <remarks/>
        public bool SignatureProofOfDeliveryAvailable {
            get {
                return this.signatureProofOfDeliveryAvailableField;
            }
            set {
                this.signatureProofOfDeliveryAvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SignatureProofOfDeliveryAvailableSpecified {
            get {
                return this.signatureProofOfDeliveryAvailableFieldSpecified;
            }
            set {
                this.signatureProofOfDeliveryAvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ProofOfDeliveryNotificationsAvailable {
            get {
                return this.proofOfDeliveryNotificationsAvailableField;
            }
            set {
                this.proofOfDeliveryNotificationsAvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProofOfDeliveryNotificationsAvailableSpecified {
            get {
                return this.proofOfDeliveryNotificationsAvailableFieldSpecified;
            }
            set {
                this.proofOfDeliveryNotificationsAvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ExceptionNotificationsAvailable {
            get {
                return this.exceptionNotificationsAvailableField;
            }
            set {
                this.exceptionNotificationsAvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExceptionNotificationsAvailableSpecified {
            get {
                return this.exceptionNotificationsAvailableFieldSpecified;
            }
            set {
                this.exceptionNotificationsAvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SplitShipmentParts")]
        public TrackSplitShipmentPart[] SplitShipmentParts {
            get {
                return this.splitShipmentPartsField;
            }
            set {
                this.splitShipmentPartsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Events")]
        public TrackEvent[] Events {
            get {
                return this.eventsField;
            }
            set {
                this.eventsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class TrackPackageIdentifier {
        
        private string valueField;
        
        private TrackIdentifierType typeField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public TrackIdentifierType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public enum TrackIdentifierType {
        
        /// <remarks/>
        BILL_OF_LADING,
        
        /// <remarks/>
        BOL,
        
        /// <remarks/>
        COD_RETURN_TRACKING_NUMBER,
        
        /// <remarks/>
        CUSTOMER_AUTHORIZATION_NUMBER,
        
        /// <remarks/>
        CUSTAUTHNUM,
        
        /// <remarks/>
        CUSTOMER_REFERENCE,
        
        /// <remarks/>
        CUR,
        
        /// <remarks/>
        DEPARTMENT,
        
        /// <remarks/>
        FREE_FORM_REFERENCE,
        
        /// <remarks/>
        GROUND_SHIPMENT_ID,
        
        /// <remarks/>
        GROUND_MPS,
        
        /// <remarks/>
        INVOICE,
        
        /// <remarks/>
        INV,
        
        /// <remarks/>
        PARTNER_CARRIER_NUMBER,
        
        /// <remarks/>
        PARTNERCARNBR,
        
        /// <remarks/>
        PART_NUMBER,
        
        /// <remarks/>
        PURCHASE_ORDER,
        
        /// <remarks/>
        RETURN_MATERIALS_AUTHORIZATION,
        
        /// <remarks/>
        RMA,
        
        /// <remarks/>
        TRACKING_CONTROL_NUMBER,
        
        /// <remarks/>
        TCN,
        
        /// <remarks/>
        TRACKING_NUMBER_OR_DOORTAG,
        
        /// <remarks/>
        SHIPPER_REFERENCE,
        
        /// <remarks/>
        STANDARD_MPS,
        
        /// <remarks/>
        SHR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/track/v2")]
    public partial class TrackReply {
        
        private NotificationSeverityType highestSeverityField;
        
        private Notification[] notificationsField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private bool duplicateWaybillField;
        
        private bool duplicateWaybillFieldSpecified;
        
        private bool moreDataField;
        
        private bool moreDataFieldSpecified;
        
        private string pagingTokenField;
        
        private TrackDetail[] trackDetailsField;
        
        /// <remarks/>
        public NotificationSeverityType HighestSeverity {
            get {
                return this.highestSeverityField;
            }
            set {
                this.highestSeverityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Notifications")]
        public Notification[] Notifications {
            get {
                return this.notificationsField;
            }
            set {
                this.notificationsField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDetail TransactionDetail {
            get {
                return this.transactionDetailField;
            }
            set {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        public VersionId Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public bool DuplicateWaybill {
            get {
                return this.duplicateWaybillField;
            }
            set {
                this.duplicateWaybillField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DuplicateWaybillSpecified {
            get {
                return this.duplicateWaybillFieldSpecified;
            }
            set {
                this.duplicateWaybillFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool MoreData {
            get {
                return this.moreDataField;
            }
            set {
                this.moreDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MoreDataSpecified {
            get {
                return this.moreDataFieldSpecified;
            }
            set {
                this.moreDataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string PagingToken {
            get {
                return this.pagingTokenField;
            }
            set {
                this.pagingTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TrackDetails")]
        public TrackDetail[] TrackDetails {
            get {
                return this.trackDetailsField;
            }
            set {
                this.trackDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void trackCompletedEventHandler(object sender, trackCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class trackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal trackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TrackReply Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TrackReply)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getTrackNotificationCompletedEventHandler(object sender, getTrackNotificationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTrackNotificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTrackNotificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TrackNotificationReply Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TrackNotificationReply)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getSignatureProofOfDeliveryCompletedEventHandler(object sender, getSignatureProofOfDeliveryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSignatureProofOfDeliveryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSignatureProofOfDeliveryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SignatureProofOfDeliveryReply Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SignatureProofOfDeliveryReply)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591