//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Receivables {
    
    public partial class CustomerPayTerms {
        protected System.Web.UI.WebControls.Panel pnlContent;
        protected System.Web.UI.UpdatePanel updtPnlContent;
        protected System.Web.UI.WebControls.Panel pnlBtnsContent;
        protected System.Web.UI.UserControl BtnsUC;
        protected System.Web.UI.WebControls.Panel pnlCPGV1Title;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcCPGV1Auto;
        protected System.Web.UI.WebControls.Panel pnlGVContent;
        protected System.Web.UI.UserControl GVUC;
        protected System.Web.UI.WebControls.Panel pnlEntryForm;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPopupHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell htcPopEntryForm;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProcessLinks;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdProcessLinks;
        protected System.Web.UI.WebControls.Panel pnlBPCContainer;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSubject;
        protected System.Web.UI.WebControls.Label lblPageSubject;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDescription;
        protected System.Web.UI.WebControls.Label lblDescription;
        protected LAjitControls.LAjitTextBox txtDescription;
        protected LAjitControls.LAjitRequiredFieldValidator reqDescription;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPayInstruct;
        protected System.Web.UI.WebControls.Label lblPayInstruct;
        protected LAjitControls.LAjitTextBox txtPayInstruct;
        protected LAjitControls.LAjitRequiredFieldValidator reqPayInstruct;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDueDays;
        protected System.Web.UI.WebControls.Label lblDueDays;
        protected LAjitControls.LAjitTextBox txtDueDays;
        protected LAjitControls.LAjitRequiredFieldValidator reqDueDays;
        protected LAjitControls.LAjitRegularExpressionValidator regDueDays;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDiscDays;
        protected System.Web.UI.WebControls.Label lblDiscDays;
        protected LAjitControls.LAjitTextBox txtDiscDays;
        protected LAjitControls.LAjitRequiredFieldValidator reqDiscDays;
        protected LAjitControls.LAjitRegularExpressionValidator regDiscDays;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDiscount;
        protected System.Web.UI.WebControls.Label lblDiscount;
        protected LAjitControls.LAjitTextBox txtDiscount;
        protected LAjitControls.LAjitRequiredFieldValidator reqDiscount;
        protected LAjitControls.LAjitRegularExpressionValidator regDiscount;
        protected System.Web.UI.HtmlControls.HtmlTableRow trOverNightIns;
        protected System.Web.UI.WebControls.Label lblOverNightIns;
        protected LAjitControls.LAjitTextBox txtOverNightIns;
        protected LAjitControls.LAjitRequiredFieldValidator reqOverNightIns;
        protected System.Web.UI.HtmlControls.HtmlTableRow trWiringInst;
        protected System.Web.UI.WebControls.Label lblWiringInst;
        protected LAjitControls.LAjitTextBox txtWiringInst;
        protected LAjitControls.LAjitRequiredFieldValidator reqWiringInst;
        protected System.Web.UI.HtmlControls.HtmlTableRow trFooterMessage;
        protected System.Web.UI.WebControls.Label lblFooterMessage;
        protected LAjitControls.LAjitTextBox txtFooterMessage;
        protected LAjitControls.LAjitRequiredFieldValidator reqFooterMessage;
        protected System.Web.UI.HtmlControls.HtmlTableRow trIsLogoPrinted;
        protected System.Web.UI.WebControls.Label lblIsLogoPrinted;
        protected LAjitControls.LAjitCheckBox chkIsLogoPrinted;
        protected System.Web.UI.HtmlControls.HtmlTableRow trLogoCaption;
        protected System.Web.UI.WebControls.Label lblLogoCaption;
        protected LAjitControls.LAjitTextBox txtLogoCaption;
        protected LAjitControls.LAjitRequiredFieldValidator reqLogoCaption;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnContinueAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAddClone;
        protected System.Web.UI.WebControls.ImageButton imgbtnCancel;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrevious;
        protected System.Web.UI.WebControls.ImageButton imgbtnNext;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.Timer timerEntryForm;
        protected System.Web.UI.WebControls.Panel pnlContentError;
        protected System.Web.UI.WebControls.Label lblError;
    }
}
