//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.PopUps {
    
    public partial class Attachement {
        protected System.Web.UI.HtmlControls.HtmlForm frmAttachement;
        protected System.Web.UI.ScriptManager AttachScriptMngr;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divInitAttachement;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDownload;
        protected System.Web.UI.WebControls.ImageButton imgbtnAttachDownload;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnAttachAdd;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDelete;
        protected System.Web.UI.WebControls.ImageButton imgbtnAttachDelete;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSecure;
        protected System.Web.UI.WebControls.ImageButton imgbtnAttachSecure;
        protected System.Web.UI.HtmlControls.HtmlTableRow trattachgrid;
        protected System.Web.UI.WebControls.GridView gvAttach;
        protected System.Web.UI.WebControls.Label lblNotesGVmsg;
        protected System.Web.UI.WebControls.Panel pnlAttachment;
        protected System.Web.UI.WebControls.Label lblDescription;
        protected LAjitControls.LAjitTextBox txtDescription;
        protected System.Web.UI.WebControls.RequiredFieldValidator reqDescription;
        protected System.Web.UI.WebControls.Label lblFileName;
        protected System.Web.UI.WebControls.FileUpload FileAttachment;
        protected System.Web.UI.WebControls.RequiredFieldValidator reqFileName;
        protected System.Web.UI.WebControls.Label lblFileType;
        protected LAjitControls.LAjitDropDownList ddlFileType;
        protected System.Web.UI.WebControls.RequiredFieldValidator reqFileType;
        protected System.Web.UI.WebControls.Label lblmsgNote;
        protected System.Web.UI.WebControls.Panel pnlSubmit;
        protected System.Web.UI.WebControls.ImageButton imgbtnAttachSubmit;
        protected System.Web.UI.WebControls.HiddenField hdnSectedRow;
        protected System.Web.UI.WebControls.HiddenField hdnFldNoteAction;
        protected System.Web.UI.WebControls.HiddenField hdnRadIndex;
        protected System.Web.UI.WebControls.HiddenField hdnParentRow;
        protected System.Web.UI.WebControls.HiddenField hdnCurrentBPGID;
        protected System.Web.UI.WebControls.HiddenField hdnButtons;
        protected System.Web.UI.WebControls.HiddenField hdnUplFullPath;
        protected System.Web.UI.WebControls.XmlDataSource xdsAttachment;
        protected System.Web.UI.WebControls.HiddenField hdfDummy;
        protected System.Web.UI.WebControls.Panel pnlNote;
        protected System.Web.UI.WebControls.ValidationSummary valSummmaryEntryForm;
    }
}
