//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.PopUps {
    
    public partial class FramePDF {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.ScriptManager pnlPrintScriptMgr;
        protected System.Web.UI.WebControls.Panel pnlTotalPrint;
        protected System.Web.UI.WebControls.Panel pnllblMsg;
        protected System.Web.UI.WebControls.Label lblMsg;
        protected System.Web.UI.WebControls.Panel pnlEmailing;
        protected System.Web.UI.HtmlControls.HtmlTableRow trEmailing;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.Label lblEmailIDS;
        protected LAjitControls.LAjitTextBox txtEmailing;
        protected LAjitControls.LAjitRegularExpressionValidator regEmailing;
        protected System.Web.UI.WebControls.Label lblNote;
        protected LAjitControls.LAjitImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.Literal littxt;
    }
}
