//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.PopUps {
    
    public partial class Notes {
        protected System.Web.UI.HtmlControls.HtmlForm frmNotes;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divNote;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnNoteAdd;
        protected System.Web.UI.HtmlControls.HtmlTableRow trModify;
        protected System.Web.UI.WebControls.ImageButton imgbtnNoteModify;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDelete;
        protected System.Web.UI.WebControls.ImageButton imgbtnNoteDelete;
        protected System.Web.UI.HtmlControls.HtmlTableRow trgview;
        protected System.Web.UI.WebControls.GridView gvNotes;
        protected System.Web.UI.WebControls.Label lblNotesGVmsg;
        protected System.Web.UI.WebControls.Panel pnlNote;
        protected System.Web.UI.WebControls.Label lblNote;
        protected LAjitControls.LAjitTextBox txtNote;
        protected System.Web.UI.WebControls.RequiredFieldValidator reqNote;
        protected System.Web.UI.WebControls.RegularExpressionValidator regNote;
        protected System.Web.UI.WebControls.Label lblSharedUpdate;
        protected System.Web.UI.WebControls.CheckBox chkAgree;
        protected System.Web.UI.WebControls.Label lblmsgNote;
        protected System.Web.UI.WebControls.ImageButton imgbtnNoteSubmit;
        protected System.Web.UI.WebControls.HiddenField hdnSectedRow;
        protected System.Web.UI.WebControls.HiddenField hdnFldNoteAction;
        protected System.Web.UI.WebControls.HiddenField hdnRadIndex;
        protected System.Web.UI.WebControls.HiddenField hdnParentRow;
        protected System.Web.UI.WebControls.HiddenField hdnButtons;
        protected System.Web.UI.WebControls.ValidationSummary valSummmaryEntryForm;
    }
}
