//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.Financials {
    
    public partial class PrintPopUp {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm frmPrintPopUp;
        protected System.Web.UI.ScriptManager pnlPrintScriptMgr;
        protected System.Web.UI.WebControls.Panel pnlTotalPrint;
        protected System.Web.UI.WebControls.Panel pnlChooseOptions;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.WebControls.Panel pnlImgButtons;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPDF;
        protected System.Web.UI.WebControls.ImageButton imgbtnPdf;
        protected System.Web.UI.HtmlControls.HtmlTableRow trExcel;
        protected System.Web.UI.WebControls.ImageButton imgbtnExcel;
        protected System.Web.UI.HtmlControls.HtmlTableRow trHtml;
        protected System.Web.UI.WebControls.ImageButton imgbtnHtml;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPrint;
        protected System.Web.UI.WebControls.ImageButton imgbtnPrintOption;
        protected System.Web.UI.WebControls.Panel pnlCurrentAll;
        protected System.Web.UI.WebControls.Label lblPage;
        protected System.Web.UI.HtmlControls.HtmlSelect lstPage;
        protected System.Web.UI.WebControls.ListItem pageYes;
        protected System.Web.UI.WebControls.ListItem pageNo;
        protected System.Web.UI.WebControls.Panel pnlExtendedCols;
        protected System.Web.UI.WebControls.Label lblExtendedCols;
        protected System.Web.UI.HtmlControls.HtmlSelect lstExtendedCols;
        protected System.Web.UI.WebControls.ListItem extColsYes;
        protected System.Web.UI.WebControls.ListItem extColsNo;
        protected System.Web.UI.WebControls.Panel pnlSavetoMyReports;
        protected System.Web.UI.WebControls.Label lblSaveToMyReports;
        protected System.Web.UI.HtmlControls.HtmlSelect lstSaveToMyReports;
        protected System.Web.UI.WebControls.ListItem saverptYes;
        protected System.Web.UI.WebControls.ListItem saverptNo;
        protected System.Web.UI.WebControls.Panel pnlDistributionList;
        protected System.Web.UI.WebControls.Label lblDistribution;
        protected System.Web.UI.HtmlControls.HtmlSelect lstDistribution;
        protected System.Web.UI.WebControls.Panel pnlChkReportRetrieve;
        protected System.Web.UI.WebControls.Label lblChkRptRetrieve;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdChkRptRetrieve;
        protected System.Web.UI.HtmlControls.HtmlSelect lstRetrieveRpt;
        protected System.Web.UI.WebControls.ListItem retrieveYes;
        protected System.Web.UI.WebControls.ListItem retrieveNo;
        protected System.Web.UI.WebControls.Panel pnllblMsg;
        protected System.Web.UI.WebControls.Label lblMsg;
        protected System.Web.UI.WebControls.Panel pnlPrintOptionBtn;
        protected System.Web.UI.WebControls.Literal litPrintOptionBtn;
        protected System.Web.UI.WebControls.Panel pnlPrinting;
        protected System.Web.UI.WebControls.Literal litPrinting;
        protected System.Web.UI.WebControls.HiddenField hdnGVReqXml;
        protected System.Web.UI.WebControls.HiddenField hdnGVRetXml;
        protected System.Web.UI.WebControls.HiddenField hdnShowPDF;
        protected System.Web.UI.WebControls.HiddenField hdnReportName;
        protected System.Web.UI.WebControls.HiddenField hdntest;
        protected System.Web.UI.WebControls.HiddenField hdnPrint;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hdnPrintReport;
    }
}
