//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAjitDev.PopUps {
    
    public partial class Secure {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lblPopupEntry;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAdd;
        protected System.Web.UI.WebControls.ImageButton imgbtnSecureAdd;
        protected System.Web.UI.HtmlControls.HtmlTableRow trModify;
        protected System.Web.UI.WebControls.ImageButton imgbtnSecureModify;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDelete;
        protected System.Web.UI.WebControls.ImageButton imgbtnSecureDelete;
        protected System.Web.UI.WebControls.Panel pnlSecure;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCreatedBy;
        protected System.Web.UI.WebControls.Label lblCreatedBy;
        protected System.Web.UI.WebControls.Label lblCreatedByData;
        protected System.Web.UI.WebControls.Label lblSecureCategory;
        protected LAjitControls.LAjitDropDownList ddlSecureCategory;
        protected System.Web.UI.WebControls.RequiredFieldValidator reqSecureCategory;
        protected System.Web.UI.WebControls.Label lblmsgNote;
        protected System.Web.UI.WebControls.ImageButton imgbtnSubmit;
        protected System.Web.UI.WebControls.HiddenField hdnSectedRow;
        protected System.Web.UI.WebControls.HiddenField hdnFldSecureAction;
        protected System.Web.UI.WebControls.HiddenField hdnRadIndex;
        protected System.Web.UI.WebControls.HiddenField hdnParentRow;
        protected System.Web.UI.WebControls.HiddenField hdnButtons;
        protected System.Web.UI.WebControls.ValidationSummary valSummmaryEntryForm;
    }
}
